package com.dlfc.contract.entity;

import com.dlfc.contract.common.DataEntity;

import java.math.BigDecimal;
import java.util.Date;

public class ConHouseItemsLog extends DataEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_items_log.ID
     *
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_items_log.PINDEX
     *
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    private Integer pindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_items_log.CID
     *
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_items_log.CON_LOG_ID
     *
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    private String conLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_items_log.ITEM
     *
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    private String item;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_items_log.BRAND
     *
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_items_log.UNIT
     *
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_items_log.NUM
     *
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_items_log.PRICE
     *
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_items_log.COMPEN_AMOUNT
     *
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    private BigDecimal compenAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_items_log.COMMENT
     *
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_items_log.CREATE_USER
     *
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_items_log.CREATE_USER_IDENTITY
     *
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    private Short createUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_items_log.CREATE_TIME
     *
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_items_log.MODIFY_USER
     *
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_items_log.MODIFY_USER_IDENTITY
     *
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    private Short modifyUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_items_log.MODIFY_TIME
     *
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_items_log.DELETE_FLG
     *
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    private Short deleteFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_items_log.VERSION
     *
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_house_items_log.ID
     *
     * @return the value of con_house_items_log.ID
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_house_items_log.ID
     *
     * @param id the value for con_house_items_log.ID
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_house_items_log.PINDEX
     *
     * @return the value of con_house_items_log.PINDEX
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public Integer getPindex() {
        return pindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_house_items_log.PINDEX
     *
     * @param pindex the value for con_house_items_log.PINDEX
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public void setPindex(Integer pindex) {
        this.pindex = pindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_house_items_log.CID
     *
     * @return the value of con_house_items_log.CID
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_house_items_log.CID
     *
     * @param cid the value for con_house_items_log.CID
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_house_items_log.CON_LOG_ID
     *
     * @return the value of con_house_items_log.CON_LOG_ID
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public String getConLogId() {
        return conLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_house_items_log.CON_LOG_ID
     *
     * @param conLogId the value for con_house_items_log.CON_LOG_ID
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public void setConLogId(String conLogId) {
        this.conLogId = conLogId == null ? null : conLogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_house_items_log.ITEM
     *
     * @return the value of con_house_items_log.ITEM
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public String getItem() {
        return item;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_house_items_log.ITEM
     *
     * @param item the value for con_house_items_log.ITEM
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public void setItem(String item) {
        this.item = item == null ? null : item.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_house_items_log.BRAND
     *
     * @return the value of con_house_items_log.BRAND
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_house_items_log.BRAND
     *
     * @param brand the value for con_house_items_log.BRAND
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_house_items_log.UNIT
     *
     * @return the value of con_house_items_log.UNIT
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_house_items_log.UNIT
     *
     * @param unit the value for con_house_items_log.UNIT
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_house_items_log.NUM
     *
     * @return the value of con_house_items_log.NUM
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_house_items_log.NUM
     *
     * @param num the value for con_house_items_log.NUM
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_house_items_log.PRICE
     *
     * @return the value of con_house_items_log.PRICE
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_house_items_log.PRICE
     *
     * @param price the value for con_house_items_log.PRICE
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_house_items_log.COMPEN_AMOUNT
     *
     * @return the value of con_house_items_log.COMPEN_AMOUNT
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public BigDecimal getCompenAmount() {
        return compenAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_house_items_log.COMPEN_AMOUNT
     *
     * @param compenAmount the value for con_house_items_log.COMPEN_AMOUNT
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public void setCompenAmount(BigDecimal compenAmount) {
        this.compenAmount = compenAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_house_items_log.COMMENT
     *
     * @return the value of con_house_items_log.COMMENT
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_house_items_log.COMMENT
     *
     * @param comment the value for con_house_items_log.COMMENT
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_house_items_log.CREATE_USER
     *
     * @return the value of con_house_items_log.CREATE_USER
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_house_items_log.CREATE_USER
     *
     * @param createUser the value for con_house_items_log.CREATE_USER
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_house_items_log.CREATE_USER_IDENTITY
     *
     * @return the value of con_house_items_log.CREATE_USER_IDENTITY
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public Short getCreateUserIdentity() {
        return createUserIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_house_items_log.CREATE_USER_IDENTITY
     *
     * @param createUserIdentity the value for con_house_items_log.CREATE_USER_IDENTITY
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public void setCreateUserIdentity(Short createUserIdentity) {
        this.createUserIdentity = createUserIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_house_items_log.CREATE_TIME
     *
     * @return the value of con_house_items_log.CREATE_TIME
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_house_items_log.CREATE_TIME
     *
     * @param createTime the value for con_house_items_log.CREATE_TIME
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_house_items_log.MODIFY_USER
     *
     * @return the value of con_house_items_log.MODIFY_USER
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_house_items_log.MODIFY_USER
     *
     * @param modifyUser the value for con_house_items_log.MODIFY_USER
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_house_items_log.MODIFY_USER_IDENTITY
     *
     * @return the value of con_house_items_log.MODIFY_USER_IDENTITY
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public Short getModifyUserIdentity() {
        return modifyUserIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_house_items_log.MODIFY_USER_IDENTITY
     *
     * @param modifyUserIdentity the value for con_house_items_log.MODIFY_USER_IDENTITY
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public void setModifyUserIdentity(Short modifyUserIdentity) {
        this.modifyUserIdentity = modifyUserIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_house_items_log.MODIFY_TIME
     *
     * @return the value of con_house_items_log.MODIFY_TIME
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_house_items_log.MODIFY_TIME
     *
     * @param modifyTime the value for con_house_items_log.MODIFY_TIME
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_house_items_log.DELETE_FLG
     *
     * @return the value of con_house_items_log.DELETE_FLG
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public Short getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_house_items_log.DELETE_FLG
     *
     * @param deleteFlg the value for con_house_items_log.DELETE_FLG
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public void setDeleteFlg(Short deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_house_items_log.VERSION
     *
     * @return the value of con_house_items_log.VERSION
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_house_items_log.VERSION
     *
     * @param version the value for con_house_items_log.VERSION
     * @mbggenerated Tue May 30 10:09:07 CST 2017
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}