package com.dlfc.agent.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AgtCompInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table agt_comp_info
     *
     * @mbggenerated Tue May 30 09:23:39 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table agt_comp_info
     *
     * @mbggenerated Tue May 30 09:23:39 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table agt_comp_info
     *
     * @mbggenerated Tue May 30 09:23:39 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_comp_info
     *
     * @mbggenerated Tue May 30 09:23:39 CST 2017
     */
    public AgtCompInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_comp_info
     *
     * @mbggenerated Tue May 30 09:23:39 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_comp_info
     *
     * @mbggenerated Tue May 30 09:23:39 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_comp_info
     *
     * @mbggenerated Tue May 30 09:23:39 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_comp_info
     *
     * @mbggenerated Tue May 30 09:23:39 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_comp_info
     *
     * @mbggenerated Tue May 30 09:23:39 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_comp_info
     *
     * @mbggenerated Tue May 30 09:23:39 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_comp_info
     *
     * @mbggenerated Tue May 30 09:23:39 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_comp_info
     *
     * @mbggenerated Tue May 30 09:23:39 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_comp_info
     *
     * @mbggenerated Tue May 30 09:23:39 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agt_comp_info
     *
     * @mbggenerated Tue May 30 09:23:39 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table agt_comp_info
     *
     * @mbggenerated Tue May 30 09:23:39 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPindexIsNull() {
            addCriterion("PINDEX is null");
            return (Criteria) this;
        }

        public Criteria andPindexIsNotNull() {
            addCriterion("PINDEX is not null");
            return (Criteria) this;
        }

        public Criteria andPindexEqualTo(Integer value) {
            addCriterion("PINDEX =", value, "pindex");
            return (Criteria) this;
        }

        public Criteria andPindexNotEqualTo(Integer value) {
            addCriterion("PINDEX <>", value, "pindex");
            return (Criteria) this;
        }

        public Criteria andPindexGreaterThan(Integer value) {
            addCriterion("PINDEX >", value, "pindex");
            return (Criteria) this;
        }

        public Criteria andPindexGreaterThanOrEqualTo(Integer value) {
            addCriterion("PINDEX >=", value, "pindex");
            return (Criteria) this;
        }

        public Criteria andPindexLessThan(Integer value) {
            addCriterion("PINDEX <", value, "pindex");
            return (Criteria) this;
        }

        public Criteria andPindexLessThanOrEqualTo(Integer value) {
            addCriterion("PINDEX <=", value, "pindex");
            return (Criteria) this;
        }

        public Criteria andPindexIn(List<Integer> values) {
            addCriterion("PINDEX in", values, "pindex");
            return (Criteria) this;
        }

        public Criteria andPindexNotIn(List<Integer> values) {
            addCriterion("PINDEX not in", values, "pindex");
            return (Criteria) this;
        }

        public Criteria andPindexBetween(Integer value1, Integer value2) {
            addCriterion("PINDEX between", value1, value2, "pindex");
            return (Criteria) this;
        }

        public Criteria andPindexNotBetween(Integer value1, Integer value2) {
            addCriterion("PINDEX not between", value1, value2, "pindex");
            return (Criteria) this;
        }

        public Criteria andComNoIsNull() {
            addCriterion("COM_NO is null");
            return (Criteria) this;
        }

        public Criteria andComNoIsNotNull() {
            addCriterion("COM_NO is not null");
            return (Criteria) this;
        }

        public Criteria andComNoEqualTo(String value) {
            addCriterion("COM_NO =", value, "comNo");
            return (Criteria) this;
        }

        public Criteria andComNoNotEqualTo(String value) {
            addCriterion("COM_NO <>", value, "comNo");
            return (Criteria) this;
        }

        public Criteria andComNoGreaterThan(String value) {
            addCriterion("COM_NO >", value, "comNo");
            return (Criteria) this;
        }

        public Criteria andComNoGreaterThanOrEqualTo(String value) {
            addCriterion("COM_NO >=", value, "comNo");
            return (Criteria) this;
        }

        public Criteria andComNoLessThan(String value) {
            addCriterion("COM_NO <", value, "comNo");
            return (Criteria) this;
        }

        public Criteria andComNoLessThanOrEqualTo(String value) {
            addCriterion("COM_NO <=", value, "comNo");
            return (Criteria) this;
        }

        public Criteria andComNoLike(String value) {
            addCriterion("COM_NO like", value, "comNo");
            return (Criteria) this;
        }

        public Criteria andComNoNotLike(String value) {
            addCriterion("COM_NO not like", value, "comNo");
            return (Criteria) this;
        }

        public Criteria andComNoIn(List<String> values) {
            addCriterion("COM_NO in", values, "comNo");
            return (Criteria) this;
        }

        public Criteria andComNoNotIn(List<String> values) {
            addCriterion("COM_NO not in", values, "comNo");
            return (Criteria) this;
        }

        public Criteria andComNoBetween(String value1, String value2) {
            addCriterion("COM_NO between", value1, value2, "comNo");
            return (Criteria) this;
        }

        public Criteria andComNoNotBetween(String value1, String value2) {
            addCriterion("COM_NO not between", value1, value2, "comNo");
            return (Criteria) this;
        }

        public Criteria andOfficeIdIsNull() {
            addCriterion("OFFICE_ID is null");
            return (Criteria) this;
        }

        public Criteria andOfficeIdIsNotNull() {
            addCriterion("OFFICE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOfficeIdEqualTo(String value) {
            addCriterion("OFFICE_ID =", value, "officeId");
            return (Criteria) this;
        }

        public Criteria andOfficeIdNotEqualTo(String value) {
            addCriterion("OFFICE_ID <>", value, "officeId");
            return (Criteria) this;
        }

        public Criteria andOfficeIdGreaterThan(String value) {
            addCriterion("OFFICE_ID >", value, "officeId");
            return (Criteria) this;
        }

        public Criteria andOfficeIdGreaterThanOrEqualTo(String value) {
            addCriterion("OFFICE_ID >=", value, "officeId");
            return (Criteria) this;
        }

        public Criteria andOfficeIdLessThan(String value) {
            addCriterion("OFFICE_ID <", value, "officeId");
            return (Criteria) this;
        }

        public Criteria andOfficeIdLessThanOrEqualTo(String value) {
            addCriterion("OFFICE_ID <=", value, "officeId");
            return (Criteria) this;
        }

        public Criteria andOfficeIdLike(String value) {
            addCriterion("OFFICE_ID like", value, "officeId");
            return (Criteria) this;
        }

        public Criteria andOfficeIdNotLike(String value) {
            addCriterion("OFFICE_ID not like", value, "officeId");
            return (Criteria) this;
        }

        public Criteria andOfficeIdIn(List<String> values) {
            addCriterion("OFFICE_ID in", values, "officeId");
            return (Criteria) this;
        }

        public Criteria andOfficeIdNotIn(List<String> values) {
            addCriterion("OFFICE_ID not in", values, "officeId");
            return (Criteria) this;
        }

        public Criteria andOfficeIdBetween(String value1, String value2) {
            addCriterion("OFFICE_ID between", value1, value2, "officeId");
            return (Criteria) this;
        }

        public Criteria andOfficeIdNotBetween(String value1, String value2) {
            addCriterion("OFFICE_ID not between", value1, value2, "officeId");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseIsNull() {
            addCriterion("BUSINESS_LICENSE is null");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseIsNotNull() {
            addCriterion("BUSINESS_LICENSE is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseEqualTo(String value) {
            addCriterion("BUSINESS_LICENSE =", value, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseNotEqualTo(String value) {
            addCriterion("BUSINESS_LICENSE <>", value, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseGreaterThan(String value) {
            addCriterion("BUSINESS_LICENSE >", value, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseGreaterThanOrEqualTo(String value) {
            addCriterion("BUSINESS_LICENSE >=", value, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseLessThan(String value) {
            addCriterion("BUSINESS_LICENSE <", value, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseLessThanOrEqualTo(String value) {
            addCriterion("BUSINESS_LICENSE <=", value, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseLike(String value) {
            addCriterion("BUSINESS_LICENSE like", value, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseNotLike(String value) {
            addCriterion("BUSINESS_LICENSE not like", value, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseIn(List<String> values) {
            addCriterion("BUSINESS_LICENSE in", values, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseNotIn(List<String> values) {
            addCriterion("BUSINESS_LICENSE not in", values, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseBetween(String value1, String value2) {
            addCriterion("BUSINESS_LICENSE between", value1, value2, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseNotBetween(String value1, String value2) {
            addCriterion("BUSINESS_LICENSE not between", value1, value2, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andOrganizationCodeIsNull() {
            addCriterion("ORGANIZATION_CODE is null");
            return (Criteria) this;
        }

        public Criteria andOrganizationCodeIsNotNull() {
            addCriterion("ORGANIZATION_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andOrganizationCodeEqualTo(String value) {
            addCriterion("ORGANIZATION_CODE =", value, "organizationCode");
            return (Criteria) this;
        }

        public Criteria andOrganizationCodeNotEqualTo(String value) {
            addCriterion("ORGANIZATION_CODE <>", value, "organizationCode");
            return (Criteria) this;
        }

        public Criteria andOrganizationCodeGreaterThan(String value) {
            addCriterion("ORGANIZATION_CODE >", value, "organizationCode");
            return (Criteria) this;
        }

        public Criteria andOrganizationCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ORGANIZATION_CODE >=", value, "organizationCode");
            return (Criteria) this;
        }

        public Criteria andOrganizationCodeLessThan(String value) {
            addCriterion("ORGANIZATION_CODE <", value, "organizationCode");
            return (Criteria) this;
        }

        public Criteria andOrganizationCodeLessThanOrEqualTo(String value) {
            addCriterion("ORGANIZATION_CODE <=", value, "organizationCode");
            return (Criteria) this;
        }

        public Criteria andOrganizationCodeLike(String value) {
            addCriterion("ORGANIZATION_CODE like", value, "organizationCode");
            return (Criteria) this;
        }

        public Criteria andOrganizationCodeNotLike(String value) {
            addCriterion("ORGANIZATION_CODE not like", value, "organizationCode");
            return (Criteria) this;
        }

        public Criteria andOrganizationCodeIn(List<String> values) {
            addCriterion("ORGANIZATION_CODE in", values, "organizationCode");
            return (Criteria) this;
        }

        public Criteria andOrganizationCodeNotIn(List<String> values) {
            addCriterion("ORGANIZATION_CODE not in", values, "organizationCode");
            return (Criteria) this;
        }

        public Criteria andOrganizationCodeBetween(String value1, String value2) {
            addCriterion("ORGANIZATION_CODE between", value1, value2, "organizationCode");
            return (Criteria) this;
        }

        public Criteria andOrganizationCodeNotBetween(String value1, String value2) {
            addCriterion("ORGANIZATION_CODE not between", value1, value2, "organizationCode");
            return (Criteria) this;
        }

        public Criteria andEchapterPathIsNull() {
            addCriterion("ECHAPTER_PATH is null");
            return (Criteria) this;
        }

        public Criteria andEchapterPathIsNotNull() {
            addCriterion("ECHAPTER_PATH is not null");
            return (Criteria) this;
        }

        public Criteria andEchapterPathEqualTo(String value) {
            addCriterion("ECHAPTER_PATH =", value, "echapterPath");
            return (Criteria) this;
        }

        public Criteria andEchapterPathNotEqualTo(String value) {
            addCriterion("ECHAPTER_PATH <>", value, "echapterPath");
            return (Criteria) this;
        }

        public Criteria andEchapterPathGreaterThan(String value) {
            addCriterion("ECHAPTER_PATH >", value, "echapterPath");
            return (Criteria) this;
        }

        public Criteria andEchapterPathGreaterThanOrEqualTo(String value) {
            addCriterion("ECHAPTER_PATH >=", value, "echapterPath");
            return (Criteria) this;
        }

        public Criteria andEchapterPathLessThan(String value) {
            addCriterion("ECHAPTER_PATH <", value, "echapterPath");
            return (Criteria) this;
        }

        public Criteria andEchapterPathLessThanOrEqualTo(String value) {
            addCriterion("ECHAPTER_PATH <=", value, "echapterPath");
            return (Criteria) this;
        }

        public Criteria andEchapterPathLike(String value) {
            addCriterion("ECHAPTER_PATH like", value, "echapterPath");
            return (Criteria) this;
        }

        public Criteria andEchapterPathNotLike(String value) {
            addCriterion("ECHAPTER_PATH not like", value, "echapterPath");
            return (Criteria) this;
        }

        public Criteria andEchapterPathIn(List<String> values) {
            addCriterion("ECHAPTER_PATH in", values, "echapterPath");
            return (Criteria) this;
        }

        public Criteria andEchapterPathNotIn(List<String> values) {
            addCriterion("ECHAPTER_PATH not in", values, "echapterPath");
            return (Criteria) this;
        }

        public Criteria andEchapterPathBetween(String value1, String value2) {
            addCriterion("ECHAPTER_PATH between", value1, value2, "echapterPath");
            return (Criteria) this;
        }

        public Criteria andEchapterPathNotBetween(String value1, String value2) {
            addCriterion("ECHAPTER_PATH not between", value1, value2, "echapterPath");
            return (Criteria) this;
        }

        public Criteria andEchapterEnabledIsNull() {
            addCriterion("ECHAPTER_ENABLED is null");
            return (Criteria) this;
        }

        public Criteria andEchapterEnabledIsNotNull() {
            addCriterion("ECHAPTER_ENABLED is not null");
            return (Criteria) this;
        }

        public Criteria andEchapterEnabledEqualTo(String value) {
            addCriterion("ECHAPTER_ENABLED =", value, "echapterEnabled");
            return (Criteria) this;
        }

        public Criteria andEchapterEnabledNotEqualTo(String value) {
            addCriterion("ECHAPTER_ENABLED <>", value, "echapterEnabled");
            return (Criteria) this;
        }

        public Criteria andEchapterEnabledGreaterThan(String value) {
            addCriterion("ECHAPTER_ENABLED >", value, "echapterEnabled");
            return (Criteria) this;
        }

        public Criteria andEchapterEnabledGreaterThanOrEqualTo(String value) {
            addCriterion("ECHAPTER_ENABLED >=", value, "echapterEnabled");
            return (Criteria) this;
        }

        public Criteria andEchapterEnabledLessThan(String value) {
            addCriterion("ECHAPTER_ENABLED <", value, "echapterEnabled");
            return (Criteria) this;
        }

        public Criteria andEchapterEnabledLessThanOrEqualTo(String value) {
            addCriterion("ECHAPTER_ENABLED <=", value, "echapterEnabled");
            return (Criteria) this;
        }

        public Criteria andEchapterEnabledLike(String value) {
            addCriterion("ECHAPTER_ENABLED like", value, "echapterEnabled");
            return (Criteria) this;
        }

        public Criteria andEchapterEnabledNotLike(String value) {
            addCriterion("ECHAPTER_ENABLED not like", value, "echapterEnabled");
            return (Criteria) this;
        }

        public Criteria andEchapterEnabledIn(List<String> values) {
            addCriterion("ECHAPTER_ENABLED in", values, "echapterEnabled");
            return (Criteria) this;
        }

        public Criteria andEchapterEnabledNotIn(List<String> values) {
            addCriterion("ECHAPTER_ENABLED not in", values, "echapterEnabled");
            return (Criteria) this;
        }

        public Criteria andEchapterEnabledBetween(String value1, String value2) {
            addCriterion("ECHAPTER_ENABLED between", value1, value2, "echapterEnabled");
            return (Criteria) this;
        }

        public Criteria andEchapterEnabledNotBetween(String value1, String value2) {
            addCriterion("ECHAPTER_ENABLED not between", value1, value2, "echapterEnabled");
            return (Criteria) this;
        }

        public Criteria andImg1IdIsNull() {
            addCriterion("IMG1_ID is null");
            return (Criteria) this;
        }

        public Criteria andImg1IdIsNotNull() {
            addCriterion("IMG1_ID is not null");
            return (Criteria) this;
        }

        public Criteria andImg1IdEqualTo(String value) {
            addCriterion("IMG1_ID =", value, "img1Id");
            return (Criteria) this;
        }

        public Criteria andImg1IdNotEqualTo(String value) {
            addCriterion("IMG1_ID <>", value, "img1Id");
            return (Criteria) this;
        }

        public Criteria andImg1IdGreaterThan(String value) {
            addCriterion("IMG1_ID >", value, "img1Id");
            return (Criteria) this;
        }

        public Criteria andImg1IdGreaterThanOrEqualTo(String value) {
            addCriterion("IMG1_ID >=", value, "img1Id");
            return (Criteria) this;
        }

        public Criteria andImg1IdLessThan(String value) {
            addCriterion("IMG1_ID <", value, "img1Id");
            return (Criteria) this;
        }

        public Criteria andImg1IdLessThanOrEqualTo(String value) {
            addCriterion("IMG1_ID <=", value, "img1Id");
            return (Criteria) this;
        }

        public Criteria andImg1IdLike(String value) {
            addCriterion("IMG1_ID like", value, "img1Id");
            return (Criteria) this;
        }

        public Criteria andImg1IdNotLike(String value) {
            addCriterion("IMG1_ID not like", value, "img1Id");
            return (Criteria) this;
        }

        public Criteria andImg1IdIn(List<String> values) {
            addCriterion("IMG1_ID in", values, "img1Id");
            return (Criteria) this;
        }

        public Criteria andImg1IdNotIn(List<String> values) {
            addCriterion("IMG1_ID not in", values, "img1Id");
            return (Criteria) this;
        }

        public Criteria andImg1IdBetween(String value1, String value2) {
            addCriterion("IMG1_ID between", value1, value2, "img1Id");
            return (Criteria) this;
        }

        public Criteria andImg1IdNotBetween(String value1, String value2) {
            addCriterion("IMG1_ID not between", value1, value2, "img1Id");
            return (Criteria) this;
        }

        public Criteria andImg2IdIsNull() {
            addCriterion("IMG2_ID is null");
            return (Criteria) this;
        }

        public Criteria andImg2IdIsNotNull() {
            addCriterion("IMG2_ID is not null");
            return (Criteria) this;
        }

        public Criteria andImg2IdEqualTo(String value) {
            addCriterion("IMG2_ID =", value, "img2Id");
            return (Criteria) this;
        }

        public Criteria andImg2IdNotEqualTo(String value) {
            addCriterion("IMG2_ID <>", value, "img2Id");
            return (Criteria) this;
        }

        public Criteria andImg2IdGreaterThan(String value) {
            addCriterion("IMG2_ID >", value, "img2Id");
            return (Criteria) this;
        }

        public Criteria andImg2IdGreaterThanOrEqualTo(String value) {
            addCriterion("IMG2_ID >=", value, "img2Id");
            return (Criteria) this;
        }

        public Criteria andImg2IdLessThan(String value) {
            addCriterion("IMG2_ID <", value, "img2Id");
            return (Criteria) this;
        }

        public Criteria andImg2IdLessThanOrEqualTo(String value) {
            addCriterion("IMG2_ID <=", value, "img2Id");
            return (Criteria) this;
        }

        public Criteria andImg2IdLike(String value) {
            addCriterion("IMG2_ID like", value, "img2Id");
            return (Criteria) this;
        }

        public Criteria andImg2IdNotLike(String value) {
            addCriterion("IMG2_ID not like", value, "img2Id");
            return (Criteria) this;
        }

        public Criteria andImg2IdIn(List<String> values) {
            addCriterion("IMG2_ID in", values, "img2Id");
            return (Criteria) this;
        }

        public Criteria andImg2IdNotIn(List<String> values) {
            addCriterion("IMG2_ID not in", values, "img2Id");
            return (Criteria) this;
        }

        public Criteria andImg2IdBetween(String value1, String value2) {
            addCriterion("IMG2_ID between", value1, value2, "img2Id");
            return (Criteria) this;
        }

        public Criteria andImg2IdNotBetween(String value1, String value2) {
            addCriterion("IMG2_ID not between", value1, value2, "img2Id");
            return (Criteria) this;
        }

        public Criteria andImg3IdIsNull() {
            addCriterion("IMG3_ID is null");
            return (Criteria) this;
        }

        public Criteria andImg3IdIsNotNull() {
            addCriterion("IMG3_ID is not null");
            return (Criteria) this;
        }

        public Criteria andImg3IdEqualTo(String value) {
            addCriterion("IMG3_ID =", value, "img3Id");
            return (Criteria) this;
        }

        public Criteria andImg3IdNotEqualTo(String value) {
            addCriterion("IMG3_ID <>", value, "img3Id");
            return (Criteria) this;
        }

        public Criteria andImg3IdGreaterThan(String value) {
            addCriterion("IMG3_ID >", value, "img3Id");
            return (Criteria) this;
        }

        public Criteria andImg3IdGreaterThanOrEqualTo(String value) {
            addCriterion("IMG3_ID >=", value, "img3Id");
            return (Criteria) this;
        }

        public Criteria andImg3IdLessThan(String value) {
            addCriterion("IMG3_ID <", value, "img3Id");
            return (Criteria) this;
        }

        public Criteria andImg3IdLessThanOrEqualTo(String value) {
            addCriterion("IMG3_ID <=", value, "img3Id");
            return (Criteria) this;
        }

        public Criteria andImg3IdLike(String value) {
            addCriterion("IMG3_ID like", value, "img3Id");
            return (Criteria) this;
        }

        public Criteria andImg3IdNotLike(String value) {
            addCriterion("IMG3_ID not like", value, "img3Id");
            return (Criteria) this;
        }

        public Criteria andImg3IdIn(List<String> values) {
            addCriterion("IMG3_ID in", values, "img3Id");
            return (Criteria) this;
        }

        public Criteria andImg3IdNotIn(List<String> values) {
            addCriterion("IMG3_ID not in", values, "img3Id");
            return (Criteria) this;
        }

        public Criteria andImg3IdBetween(String value1, String value2) {
            addCriterion("IMG3_ID between", value1, value2, "img3Id");
            return (Criteria) this;
        }

        public Criteria andImg3IdNotBetween(String value1, String value2) {
            addCriterion("IMG3_ID not between", value1, value2, "img3Id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andFullNameIsNull() {
            addCriterion("FULL_NAME is null");
            return (Criteria) this;
        }

        public Criteria andFullNameIsNotNull() {
            addCriterion("FULL_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andFullNameEqualTo(String value) {
            addCriterion("FULL_NAME =", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameNotEqualTo(String value) {
            addCriterion("FULL_NAME <>", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameGreaterThan(String value) {
            addCriterion("FULL_NAME >", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameGreaterThanOrEqualTo(String value) {
            addCriterion("FULL_NAME >=", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameLessThan(String value) {
            addCriterion("FULL_NAME <", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameLessThanOrEqualTo(String value) {
            addCriterion("FULL_NAME <=", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameLike(String value) {
            addCriterion("FULL_NAME like", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameNotLike(String value) {
            addCriterion("FULL_NAME not like", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameIn(List<String> values) {
            addCriterion("FULL_NAME in", values, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameNotIn(List<String> values) {
            addCriterion("FULL_NAME not in", values, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameBetween(String value1, String value2) {
            addCriterion("FULL_NAME between", value1, value2, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameNotBetween(String value1, String value2) {
            addCriterion("FULL_NAME not between", value1, value2, "fullName");
            return (Criteria) this;
        }

        public Criteria andSSpellingIsNull() {
            addCriterion("S_SPELLING is null");
            return (Criteria) this;
        }

        public Criteria andSSpellingIsNotNull() {
            addCriterion("S_SPELLING is not null");
            return (Criteria) this;
        }

        public Criteria andSSpellingEqualTo(String value) {
            addCriterion("S_SPELLING =", value, "sSpelling");
            return (Criteria) this;
        }

        public Criteria andSSpellingNotEqualTo(String value) {
            addCriterion("S_SPELLING <>", value, "sSpelling");
            return (Criteria) this;
        }

        public Criteria andSSpellingGreaterThan(String value) {
            addCriterion("S_SPELLING >", value, "sSpelling");
            return (Criteria) this;
        }

        public Criteria andSSpellingGreaterThanOrEqualTo(String value) {
            addCriterion("S_SPELLING >=", value, "sSpelling");
            return (Criteria) this;
        }

        public Criteria andSSpellingLessThan(String value) {
            addCriterion("S_SPELLING <", value, "sSpelling");
            return (Criteria) this;
        }

        public Criteria andSSpellingLessThanOrEqualTo(String value) {
            addCriterion("S_SPELLING <=", value, "sSpelling");
            return (Criteria) this;
        }

        public Criteria andSSpellingLike(String value) {
            addCriterion("S_SPELLING like", value, "sSpelling");
            return (Criteria) this;
        }

        public Criteria andSSpellingNotLike(String value) {
            addCriterion("S_SPELLING not like", value, "sSpelling");
            return (Criteria) this;
        }

        public Criteria andSSpellingIn(List<String> values) {
            addCriterion("S_SPELLING in", values, "sSpelling");
            return (Criteria) this;
        }

        public Criteria andSSpellingNotIn(List<String> values) {
            addCriterion("S_SPELLING not in", values, "sSpelling");
            return (Criteria) this;
        }

        public Criteria andSSpellingBetween(String value1, String value2) {
            addCriterion("S_SPELLING between", value1, value2, "sSpelling");
            return (Criteria) this;
        }

        public Criteria andSSpellingNotBetween(String value1, String value2) {
            addCriterion("S_SPELLING not between", value1, value2, "sSpelling");
            return (Criteria) this;
        }

        public Criteria andASpellingIsNull() {
            addCriterion("A_SPELLING is null");
            return (Criteria) this;
        }

        public Criteria andASpellingIsNotNull() {
            addCriterion("A_SPELLING is not null");
            return (Criteria) this;
        }

        public Criteria andASpellingEqualTo(String value) {
            addCriterion("A_SPELLING =", value, "aSpelling");
            return (Criteria) this;
        }

        public Criteria andASpellingNotEqualTo(String value) {
            addCriterion("A_SPELLING <>", value, "aSpelling");
            return (Criteria) this;
        }

        public Criteria andASpellingGreaterThan(String value) {
            addCriterion("A_SPELLING >", value, "aSpelling");
            return (Criteria) this;
        }

        public Criteria andASpellingGreaterThanOrEqualTo(String value) {
            addCriterion("A_SPELLING >=", value, "aSpelling");
            return (Criteria) this;
        }

        public Criteria andASpellingLessThan(String value) {
            addCriterion("A_SPELLING <", value, "aSpelling");
            return (Criteria) this;
        }

        public Criteria andASpellingLessThanOrEqualTo(String value) {
            addCriterion("A_SPELLING <=", value, "aSpelling");
            return (Criteria) this;
        }

        public Criteria andASpellingLike(String value) {
            addCriterion("A_SPELLING like", value, "aSpelling");
            return (Criteria) this;
        }

        public Criteria andASpellingNotLike(String value) {
            addCriterion("A_SPELLING not like", value, "aSpelling");
            return (Criteria) this;
        }

        public Criteria andASpellingIn(List<String> values) {
            addCriterion("A_SPELLING in", values, "aSpelling");
            return (Criteria) this;
        }

        public Criteria andASpellingNotIn(List<String> values) {
            addCriterion("A_SPELLING not in", values, "aSpelling");
            return (Criteria) this;
        }

        public Criteria andASpellingBetween(String value1, String value2) {
            addCriterion("A_SPELLING between", value1, value2, "aSpelling");
            return (Criteria) this;
        }

        public Criteria andASpellingNotBetween(String value1, String value2) {
            addCriterion("A_SPELLING not between", value1, value2, "aSpelling");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("ADDRESS =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("ADDRESS <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("ADDRESS >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("ADDRESS <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("ADDRESS <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("ADDRESS like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("ADDRESS not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("ADDRESS in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("ADDRESS not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("ADDRESS between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("ADDRESS not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andLegalPersonIsNull() {
            addCriterion("LEGAL_PERSON is null");
            return (Criteria) this;
        }

        public Criteria andLegalPersonIsNotNull() {
            addCriterion("LEGAL_PERSON is not null");
            return (Criteria) this;
        }

        public Criteria andLegalPersonEqualTo(String value) {
            addCriterion("LEGAL_PERSON =", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonNotEqualTo(String value) {
            addCriterion("LEGAL_PERSON <>", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonGreaterThan(String value) {
            addCriterion("LEGAL_PERSON >", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonGreaterThanOrEqualTo(String value) {
            addCriterion("LEGAL_PERSON >=", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonLessThan(String value) {
            addCriterion("LEGAL_PERSON <", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonLessThanOrEqualTo(String value) {
            addCriterion("LEGAL_PERSON <=", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonLike(String value) {
            addCriterion("LEGAL_PERSON like", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonNotLike(String value) {
            addCriterion("LEGAL_PERSON not like", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonIn(List<String> values) {
            addCriterion("LEGAL_PERSON in", values, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonNotIn(List<String> values) {
            addCriterion("LEGAL_PERSON not in", values, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonBetween(String value1, String value2) {
            addCriterion("LEGAL_PERSON between", value1, value2, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonNotBetween(String value1, String value2) {
            addCriterion("LEGAL_PERSON not between", value1, value2, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLpMobileIsNull() {
            addCriterion("LP_MOBILE is null");
            return (Criteria) this;
        }

        public Criteria andLpMobileIsNotNull() {
            addCriterion("LP_MOBILE is not null");
            return (Criteria) this;
        }

        public Criteria andLpMobileEqualTo(String value) {
            addCriterion("LP_MOBILE =", value, "lpMobile");
            return (Criteria) this;
        }

        public Criteria andLpMobileNotEqualTo(String value) {
            addCriterion("LP_MOBILE <>", value, "lpMobile");
            return (Criteria) this;
        }

        public Criteria andLpMobileGreaterThan(String value) {
            addCriterion("LP_MOBILE >", value, "lpMobile");
            return (Criteria) this;
        }

        public Criteria andLpMobileGreaterThanOrEqualTo(String value) {
            addCriterion("LP_MOBILE >=", value, "lpMobile");
            return (Criteria) this;
        }

        public Criteria andLpMobileLessThan(String value) {
            addCriterion("LP_MOBILE <", value, "lpMobile");
            return (Criteria) this;
        }

        public Criteria andLpMobileLessThanOrEqualTo(String value) {
            addCriterion("LP_MOBILE <=", value, "lpMobile");
            return (Criteria) this;
        }

        public Criteria andLpMobileLike(String value) {
            addCriterion("LP_MOBILE like", value, "lpMobile");
            return (Criteria) this;
        }

        public Criteria andLpMobileNotLike(String value) {
            addCriterion("LP_MOBILE not like", value, "lpMobile");
            return (Criteria) this;
        }

        public Criteria andLpMobileIn(List<String> values) {
            addCriterion("LP_MOBILE in", values, "lpMobile");
            return (Criteria) this;
        }

        public Criteria andLpMobileNotIn(List<String> values) {
            addCriterion("LP_MOBILE not in", values, "lpMobile");
            return (Criteria) this;
        }

        public Criteria andLpMobileBetween(String value1, String value2) {
            addCriterion("LP_MOBILE between", value1, value2, "lpMobile");
            return (Criteria) this;
        }

        public Criteria andLpMobileNotBetween(String value1, String value2) {
            addCriterion("LP_MOBILE not between", value1, value2, "lpMobile");
            return (Criteria) this;
        }

        public Criteria andLpIdcardIsNull() {
            addCriterion("LP_IDCARD is null");
            return (Criteria) this;
        }

        public Criteria andLpIdcardIsNotNull() {
            addCriterion("LP_IDCARD is not null");
            return (Criteria) this;
        }

        public Criteria andLpIdcardEqualTo(String value) {
            addCriterion("LP_IDCARD =", value, "lpIdcard");
            return (Criteria) this;
        }

        public Criteria andLpIdcardNotEqualTo(String value) {
            addCriterion("LP_IDCARD <>", value, "lpIdcard");
            return (Criteria) this;
        }

        public Criteria andLpIdcardGreaterThan(String value) {
            addCriterion("LP_IDCARD >", value, "lpIdcard");
            return (Criteria) this;
        }

        public Criteria andLpIdcardGreaterThanOrEqualTo(String value) {
            addCriterion("LP_IDCARD >=", value, "lpIdcard");
            return (Criteria) this;
        }

        public Criteria andLpIdcardLessThan(String value) {
            addCriterion("LP_IDCARD <", value, "lpIdcard");
            return (Criteria) this;
        }

        public Criteria andLpIdcardLessThanOrEqualTo(String value) {
            addCriterion("LP_IDCARD <=", value, "lpIdcard");
            return (Criteria) this;
        }

        public Criteria andLpIdcardLike(String value) {
            addCriterion("LP_IDCARD like", value, "lpIdcard");
            return (Criteria) this;
        }

        public Criteria andLpIdcardNotLike(String value) {
            addCriterion("LP_IDCARD not like", value, "lpIdcard");
            return (Criteria) this;
        }

        public Criteria andLpIdcardIn(List<String> values) {
            addCriterion("LP_IDCARD in", values, "lpIdcard");
            return (Criteria) this;
        }

        public Criteria andLpIdcardNotIn(List<String> values) {
            addCriterion("LP_IDCARD not in", values, "lpIdcard");
            return (Criteria) this;
        }

        public Criteria andLpIdcardBetween(String value1, String value2) {
            addCriterion("LP_IDCARD between", value1, value2, "lpIdcard");
            return (Criteria) this;
        }

        public Criteria andLpIdcardNotBetween(String value1, String value2) {
            addCriterion("LP_IDCARD not between", value1, value2, "lpIdcard");
            return (Criteria) this;
        }

        public Criteria andContactPersonIsNull() {
            addCriterion("CONTACT_PERSON is null");
            return (Criteria) this;
        }

        public Criteria andContactPersonIsNotNull() {
            addCriterion("CONTACT_PERSON is not null");
            return (Criteria) this;
        }

        public Criteria andContactPersonEqualTo(String value) {
            addCriterion("CONTACT_PERSON =", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonNotEqualTo(String value) {
            addCriterion("CONTACT_PERSON <>", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonGreaterThan(String value) {
            addCriterion("CONTACT_PERSON >", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonGreaterThanOrEqualTo(String value) {
            addCriterion("CONTACT_PERSON >=", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonLessThan(String value) {
            addCriterion("CONTACT_PERSON <", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonLessThanOrEqualTo(String value) {
            addCriterion("CONTACT_PERSON <=", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonLike(String value) {
            addCriterion("CONTACT_PERSON like", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonNotLike(String value) {
            addCriterion("CONTACT_PERSON not like", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonIn(List<String> values) {
            addCriterion("CONTACT_PERSON in", values, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonNotIn(List<String> values) {
            addCriterion("CONTACT_PERSON not in", values, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonBetween(String value1, String value2) {
            addCriterion("CONTACT_PERSON between", value1, value2, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonNotBetween(String value1, String value2) {
            addCriterion("CONTACT_PERSON not between", value1, value2, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andCpMobileIsNull() {
            addCriterion("CP_MOBILE is null");
            return (Criteria) this;
        }

        public Criteria andCpMobileIsNotNull() {
            addCriterion("CP_MOBILE is not null");
            return (Criteria) this;
        }

        public Criteria andCpMobileEqualTo(String value) {
            addCriterion("CP_MOBILE =", value, "cpMobile");
            return (Criteria) this;
        }

        public Criteria andCpMobileNotEqualTo(String value) {
            addCriterion("CP_MOBILE <>", value, "cpMobile");
            return (Criteria) this;
        }

        public Criteria andCpMobileGreaterThan(String value) {
            addCriterion("CP_MOBILE >", value, "cpMobile");
            return (Criteria) this;
        }

        public Criteria andCpMobileGreaterThanOrEqualTo(String value) {
            addCriterion("CP_MOBILE >=", value, "cpMobile");
            return (Criteria) this;
        }

        public Criteria andCpMobileLessThan(String value) {
            addCriterion("CP_MOBILE <", value, "cpMobile");
            return (Criteria) this;
        }

        public Criteria andCpMobileLessThanOrEqualTo(String value) {
            addCriterion("CP_MOBILE <=", value, "cpMobile");
            return (Criteria) this;
        }

        public Criteria andCpMobileLike(String value) {
            addCriterion("CP_MOBILE like", value, "cpMobile");
            return (Criteria) this;
        }

        public Criteria andCpMobileNotLike(String value) {
            addCriterion("CP_MOBILE not like", value, "cpMobile");
            return (Criteria) this;
        }

        public Criteria andCpMobileIn(List<String> values) {
            addCriterion("CP_MOBILE in", values, "cpMobile");
            return (Criteria) this;
        }

        public Criteria andCpMobileNotIn(List<String> values) {
            addCriterion("CP_MOBILE not in", values, "cpMobile");
            return (Criteria) this;
        }

        public Criteria andCpMobileBetween(String value1, String value2) {
            addCriterion("CP_MOBILE between", value1, value2, "cpMobile");
            return (Criteria) this;
        }

        public Criteria andCpMobileNotBetween(String value1, String value2) {
            addCriterion("CP_MOBILE not between", value1, value2, "cpMobile");
            return (Criteria) this;
        }

        public Criteria andCpIdcardIsNull() {
            addCriterion("CP_IDCARD is null");
            return (Criteria) this;
        }

        public Criteria andCpIdcardIsNotNull() {
            addCriterion("CP_IDCARD is not null");
            return (Criteria) this;
        }

        public Criteria andCpIdcardEqualTo(String value) {
            addCriterion("CP_IDCARD =", value, "cpIdcard");
            return (Criteria) this;
        }

        public Criteria andCpIdcardNotEqualTo(String value) {
            addCriterion("CP_IDCARD <>", value, "cpIdcard");
            return (Criteria) this;
        }

        public Criteria andCpIdcardGreaterThan(String value) {
            addCriterion("CP_IDCARD >", value, "cpIdcard");
            return (Criteria) this;
        }

        public Criteria andCpIdcardGreaterThanOrEqualTo(String value) {
            addCriterion("CP_IDCARD >=", value, "cpIdcard");
            return (Criteria) this;
        }

        public Criteria andCpIdcardLessThan(String value) {
            addCriterion("CP_IDCARD <", value, "cpIdcard");
            return (Criteria) this;
        }

        public Criteria andCpIdcardLessThanOrEqualTo(String value) {
            addCriterion("CP_IDCARD <=", value, "cpIdcard");
            return (Criteria) this;
        }

        public Criteria andCpIdcardLike(String value) {
            addCriterion("CP_IDCARD like", value, "cpIdcard");
            return (Criteria) this;
        }

        public Criteria andCpIdcardNotLike(String value) {
            addCriterion("CP_IDCARD not like", value, "cpIdcard");
            return (Criteria) this;
        }

        public Criteria andCpIdcardIn(List<String> values) {
            addCriterion("CP_IDCARD in", values, "cpIdcard");
            return (Criteria) this;
        }

        public Criteria andCpIdcardNotIn(List<String> values) {
            addCriterion("CP_IDCARD not in", values, "cpIdcard");
            return (Criteria) this;
        }

        public Criteria andCpIdcardBetween(String value1, String value2) {
            addCriterion("CP_IDCARD between", value1, value2, "cpIdcard");
            return (Criteria) this;
        }

        public Criteria andCpIdcardNotBetween(String value1, String value2) {
            addCriterion("CP_IDCARD not between", value1, value2, "cpIdcard");
            return (Criteria) this;
        }

        public Criteria andAdminIdIsNull() {
            addCriterion("ADMIN_ID is null");
            return (Criteria) this;
        }

        public Criteria andAdminIdIsNotNull() {
            addCriterion("ADMIN_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAdminIdEqualTo(String value) {
            addCriterion("ADMIN_ID =", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotEqualTo(String value) {
            addCriterion("ADMIN_ID <>", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdGreaterThan(String value) {
            addCriterion("ADMIN_ID >", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdGreaterThanOrEqualTo(String value) {
            addCriterion("ADMIN_ID >=", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdLessThan(String value) {
            addCriterion("ADMIN_ID <", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdLessThanOrEqualTo(String value) {
            addCriterion("ADMIN_ID <=", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdLike(String value) {
            addCriterion("ADMIN_ID like", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotLike(String value) {
            addCriterion("ADMIN_ID not like", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdIn(List<String> values) {
            addCriterion("ADMIN_ID in", values, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotIn(List<String> values) {
            addCriterion("ADMIN_ID not in", values, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdBetween(String value1, String value2) {
            addCriterion("ADMIN_ID between", value1, value2, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotBetween(String value1, String value2) {
            addCriterion("ADMIN_ID not between", value1, value2, "adminId");
            return (Criteria) this;
        }

        public Criteria andTelIsNull() {
            addCriterion("TEL is null");
            return (Criteria) this;
        }

        public Criteria andTelIsNotNull() {
            addCriterion("TEL is not null");
            return (Criteria) this;
        }

        public Criteria andTelEqualTo(String value) {
            addCriterion("TEL =", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotEqualTo(String value) {
            addCriterion("TEL <>", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThan(String value) {
            addCriterion("TEL >", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThanOrEqualTo(String value) {
            addCriterion("TEL >=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThan(String value) {
            addCriterion("TEL <", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThanOrEqualTo(String value) {
            addCriterion("TEL <=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLike(String value) {
            addCriterion("TEL like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotLike(String value) {
            addCriterion("TEL not like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelIn(List<String> values) {
            addCriterion("TEL in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotIn(List<String> values) {
            addCriterion("TEL not in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelBetween(String value1, String value2) {
            addCriterion("TEL between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotBetween(String value1, String value2) {
            addCriterion("TEL not between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andLicenseDateIsNull() {
            addCriterion("LICENSE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLicenseDateIsNotNull() {
            addCriterion("LICENSE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLicenseDateEqualTo(Date value) {
            addCriterion("LICENSE_DATE =", value, "licenseDate");
            return (Criteria) this;
        }

        public Criteria andLicenseDateNotEqualTo(Date value) {
            addCriterion("LICENSE_DATE <>", value, "licenseDate");
            return (Criteria) this;
        }

        public Criteria andLicenseDateGreaterThan(Date value) {
            addCriterion("LICENSE_DATE >", value, "licenseDate");
            return (Criteria) this;
        }

        public Criteria andLicenseDateGreaterThanOrEqualTo(Date value) {
            addCriterion("LICENSE_DATE >=", value, "licenseDate");
            return (Criteria) this;
        }

        public Criteria andLicenseDateLessThan(Date value) {
            addCriterion("LICENSE_DATE <", value, "licenseDate");
            return (Criteria) this;
        }

        public Criteria andLicenseDateLessThanOrEqualTo(Date value) {
            addCriterion("LICENSE_DATE <=", value, "licenseDate");
            return (Criteria) this;
        }

        public Criteria andLicenseDateIn(List<Date> values) {
            addCriterion("LICENSE_DATE in", values, "licenseDate");
            return (Criteria) this;
        }

        public Criteria andLicenseDateNotIn(List<Date> values) {
            addCriterion("LICENSE_DATE not in", values, "licenseDate");
            return (Criteria) this;
        }

        public Criteria andLicenseDateBetween(Date value1, Date value2) {
            addCriterion("LICENSE_DATE between", value1, value2, "licenseDate");
            return (Criteria) this;
        }

        public Criteria andLicenseDateNotBetween(Date value1, Date value2) {
            addCriterion("LICENSE_DATE not between", value1, value2, "licenseDate");
            return (Criteria) this;
        }

        public Criteria andLockFlagIsNull() {
            addCriterion("LOCK_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andLockFlagIsNotNull() {
            addCriterion("LOCK_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andLockFlagEqualTo(Integer value) {
            addCriterion("LOCK_FLAG =", value, "lockFlag");
            return (Criteria) this;
        }

        public Criteria andLockFlagNotEqualTo(Integer value) {
            addCriterion("LOCK_FLAG <>", value, "lockFlag");
            return (Criteria) this;
        }

        public Criteria andLockFlagGreaterThan(Integer value) {
            addCriterion("LOCK_FLAG >", value, "lockFlag");
            return (Criteria) this;
        }

        public Criteria andLockFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("LOCK_FLAG >=", value, "lockFlag");
            return (Criteria) this;
        }

        public Criteria andLockFlagLessThan(Integer value) {
            addCriterion("LOCK_FLAG <", value, "lockFlag");
            return (Criteria) this;
        }

        public Criteria andLockFlagLessThanOrEqualTo(Integer value) {
            addCriterion("LOCK_FLAG <=", value, "lockFlag");
            return (Criteria) this;
        }

        public Criteria andLockFlagIn(List<Integer> values) {
            addCriterion("LOCK_FLAG in", values, "lockFlag");
            return (Criteria) this;
        }

        public Criteria andLockFlagNotIn(List<Integer> values) {
            addCriterion("LOCK_FLAG not in", values, "lockFlag");
            return (Criteria) this;
        }

        public Criteria andLockFlagBetween(Integer value1, Integer value2) {
            addCriterion("LOCK_FLAG between", value1, value2, "lockFlag");
            return (Criteria) this;
        }

        public Criteria andLockFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("LOCK_FLAG not between", value1, value2, "lockFlag");
            return (Criteria) this;
        }

        public Criteria andCommissionRateIsNull() {
            addCriterion("COMMISSION_RATE is null");
            return (Criteria) this;
        }

        public Criteria andCommissionRateIsNotNull() {
            addCriterion("COMMISSION_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andCommissionRateEqualTo(BigDecimal value) {
            addCriterion("COMMISSION_RATE =", value, "commissionRate");
            return (Criteria) this;
        }

        public Criteria andCommissionRateNotEqualTo(BigDecimal value) {
            addCriterion("COMMISSION_RATE <>", value, "commissionRate");
            return (Criteria) this;
        }

        public Criteria andCommissionRateGreaterThan(BigDecimal value) {
            addCriterion("COMMISSION_RATE >", value, "commissionRate");
            return (Criteria) this;
        }

        public Criteria andCommissionRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("COMMISSION_RATE >=", value, "commissionRate");
            return (Criteria) this;
        }

        public Criteria andCommissionRateLessThan(BigDecimal value) {
            addCriterion("COMMISSION_RATE <", value, "commissionRate");
            return (Criteria) this;
        }

        public Criteria andCommissionRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("COMMISSION_RATE <=", value, "commissionRate");
            return (Criteria) this;
        }

        public Criteria andCommissionRateIn(List<BigDecimal> values) {
            addCriterion("COMMISSION_RATE in", values, "commissionRate");
            return (Criteria) this;
        }

        public Criteria andCommissionRateNotIn(List<BigDecimal> values) {
            addCriterion("COMMISSION_RATE not in", values, "commissionRate");
            return (Criteria) this;
        }

        public Criteria andCommissionRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COMMISSION_RATE between", value1, value2, "commissionRate");
            return (Criteria) this;
        }

        public Criteria andCommissionRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COMMISSION_RATE not between", value1, value2, "commissionRate");
            return (Criteria) this;
        }

        public Criteria andGradeIsNull() {
            addCriterion("GRADE is null");
            return (Criteria) this;
        }

        public Criteria andGradeIsNotNull() {
            addCriterion("GRADE is not null");
            return (Criteria) this;
        }

        public Criteria andGradeEqualTo(Integer value) {
            addCriterion("GRADE =", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotEqualTo(Integer value) {
            addCriterion("GRADE <>", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThan(Integer value) {
            addCriterion("GRADE >", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThanOrEqualTo(Integer value) {
            addCriterion("GRADE >=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThan(Integer value) {
            addCriterion("GRADE <", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThanOrEqualTo(Integer value) {
            addCriterion("GRADE <=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeIn(List<Integer> values) {
            addCriterion("GRADE in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotIn(List<Integer> values) {
            addCriterion("GRADE not in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeBetween(Integer value1, Integer value2) {
            addCriterion("GRADE between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotBetween(Integer value1, Integer value2) {
            addCriterion("GRADE not between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andPopularIsNull() {
            addCriterion("POPULAR is null");
            return (Criteria) this;
        }

        public Criteria andPopularIsNotNull() {
            addCriterion("POPULAR is not null");
            return (Criteria) this;
        }

        public Criteria andPopularEqualTo(Integer value) {
            addCriterion("POPULAR =", value, "popular");
            return (Criteria) this;
        }

        public Criteria andPopularNotEqualTo(Integer value) {
            addCriterion("POPULAR <>", value, "popular");
            return (Criteria) this;
        }

        public Criteria andPopularGreaterThan(Integer value) {
            addCriterion("POPULAR >", value, "popular");
            return (Criteria) this;
        }

        public Criteria andPopularGreaterThanOrEqualTo(Integer value) {
            addCriterion("POPULAR >=", value, "popular");
            return (Criteria) this;
        }

        public Criteria andPopularLessThan(Integer value) {
            addCriterion("POPULAR <", value, "popular");
            return (Criteria) this;
        }

        public Criteria andPopularLessThanOrEqualTo(Integer value) {
            addCriterion("POPULAR <=", value, "popular");
            return (Criteria) this;
        }

        public Criteria andPopularIn(List<Integer> values) {
            addCriterion("POPULAR in", values, "popular");
            return (Criteria) this;
        }

        public Criteria andPopularNotIn(List<Integer> values) {
            addCriterion("POPULAR not in", values, "popular");
            return (Criteria) this;
        }

        public Criteria andPopularBetween(Integer value1, Integer value2) {
            addCriterion("POPULAR between", value1, value2, "popular");
            return (Criteria) this;
        }

        public Criteria andPopularNotBetween(Integer value1, Integer value2) {
            addCriterion("POPULAR not between", value1, value2, "popular");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("CREATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("CREATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("CREATE_USER =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("CREATE_USER <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("CREATE_USER >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("CREATE_USER <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("CREATE_USER like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("CREATE_USER not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("CREATE_USER in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("CREATE_USER not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("CREATE_USER between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdentityIsNull() {
            addCriterion("CREATE_USER_IDENTITY is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdentityIsNotNull() {
            addCriterion("CREATE_USER_IDENTITY is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdentityEqualTo(Short value) {
            addCriterion("CREATE_USER_IDENTITY =", value, "createUserIdentity");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdentityNotEqualTo(Short value) {
            addCriterion("CREATE_USER_IDENTITY <>", value, "createUserIdentity");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdentityGreaterThan(Short value) {
            addCriterion("CREATE_USER_IDENTITY >", value, "createUserIdentity");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdentityGreaterThanOrEqualTo(Short value) {
            addCriterion("CREATE_USER_IDENTITY >=", value, "createUserIdentity");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdentityLessThan(Short value) {
            addCriterion("CREATE_USER_IDENTITY <", value, "createUserIdentity");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdentityLessThanOrEqualTo(Short value) {
            addCriterion("CREATE_USER_IDENTITY <=", value, "createUserIdentity");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdentityIn(List<Short> values) {
            addCriterion("CREATE_USER_IDENTITY in", values, "createUserIdentity");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdentityNotIn(List<Short> values) {
            addCriterion("CREATE_USER_IDENTITY not in", values, "createUserIdentity");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdentityBetween(Short value1, Short value2) {
            addCriterion("CREATE_USER_IDENTITY between", value1, value2, "createUserIdentity");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdentityNotBetween(Short value1, Short value2) {
            addCriterion("CREATE_USER_IDENTITY not between", value1, value2, "createUserIdentity");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNull() {
            addCriterion("MODIFY_USER is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNotNull() {
            addCriterion("MODIFY_USER is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserEqualTo(String value) {
            addCriterion("MODIFY_USER =", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotEqualTo(String value) {
            addCriterion("MODIFY_USER <>", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThan(String value) {
            addCriterion("MODIFY_USER >", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFY_USER >=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThan(String value) {
            addCriterion("MODIFY_USER <", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThanOrEqualTo(String value) {
            addCriterion("MODIFY_USER <=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLike(String value) {
            addCriterion("MODIFY_USER like", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotLike(String value) {
            addCriterion("MODIFY_USER not like", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserIn(List<String> values) {
            addCriterion("MODIFY_USER in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotIn(List<String> values) {
            addCriterion("MODIFY_USER not in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserBetween(String value1, String value2) {
            addCriterion("MODIFY_USER between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotBetween(String value1, String value2) {
            addCriterion("MODIFY_USER not between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdentityIsNull() {
            addCriterion("MODIFY_USER_IDENTITY is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdentityIsNotNull() {
            addCriterion("MODIFY_USER_IDENTITY is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdentityEqualTo(Short value) {
            addCriterion("MODIFY_USER_IDENTITY =", value, "modifyUserIdentity");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdentityNotEqualTo(Short value) {
            addCriterion("MODIFY_USER_IDENTITY <>", value, "modifyUserIdentity");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdentityGreaterThan(Short value) {
            addCriterion("MODIFY_USER_IDENTITY >", value, "modifyUserIdentity");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdentityGreaterThanOrEqualTo(Short value) {
            addCriterion("MODIFY_USER_IDENTITY >=", value, "modifyUserIdentity");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdentityLessThan(Short value) {
            addCriterion("MODIFY_USER_IDENTITY <", value, "modifyUserIdentity");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdentityLessThanOrEqualTo(Short value) {
            addCriterion("MODIFY_USER_IDENTITY <=", value, "modifyUserIdentity");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdentityIn(List<Short> values) {
            addCriterion("MODIFY_USER_IDENTITY in", values, "modifyUserIdentity");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdentityNotIn(List<Short> values) {
            addCriterion("MODIFY_USER_IDENTITY not in", values, "modifyUserIdentity");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdentityBetween(Short value1, Short value2) {
            addCriterion("MODIFY_USER_IDENTITY between", value1, value2, "modifyUserIdentity");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdentityNotBetween(Short value1, Short value2) {
            addCriterion("MODIFY_USER_IDENTITY not between", value1, value2, "modifyUserIdentity");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("MODIFY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("MODIFY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("MODIFY_TIME =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("MODIFY_TIME <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("MODIFY_TIME >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("MODIFY_TIME <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("MODIFY_TIME in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("MODIFY_TIME not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIsNull() {
            addCriterion("DELETE_FLG is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIsNotNull() {
            addCriterion("DELETE_FLG is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgEqualTo(Short value) {
            addCriterion("DELETE_FLG =", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotEqualTo(Short value) {
            addCriterion("DELETE_FLG <>", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgGreaterThan(Short value) {
            addCriterion("DELETE_FLG >", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgGreaterThanOrEqualTo(Short value) {
            addCriterion("DELETE_FLG >=", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLessThan(Short value) {
            addCriterion("DELETE_FLG <", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLessThanOrEqualTo(Short value) {
            addCriterion("DELETE_FLG <=", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIn(List<Short> values) {
            addCriterion("DELETE_FLG in", values, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotIn(List<Short> values) {
            addCriterion("DELETE_FLG not in", values, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgBetween(Short value1, Short value2) {
            addCriterion("DELETE_FLG between", value1, value2, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotBetween(Short value1, Short value2) {
            addCriterion("DELETE_FLG not between", value1, value2, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("VERSION =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("VERSION <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("VERSION >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("VERSION >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("VERSION <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("VERSION <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("VERSION in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("VERSION not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("VERSION between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("VERSION not between", value1, value2, "version");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table agt_comp_info
     *
     * @mbggenerated do_not_delete_during_merge Tue May 30 09:23:39 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table agt_comp_info
     *
     * @mbggenerated Tue May 30 09:23:39 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}