server:
  port: 18084
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.32.156.86:3306/dlfc_155?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  application:
    name: dlfc-datacenter-system
mybatis:
  config-location: classpath:mybatis-config.xml
  mapperLocations: classpath:mappings/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-2:11112/eureka,http://eureka-server-3:11113/eureka