package com.dlfc.system.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_order
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_order
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_order
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    public SysOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_order
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPindexIsNull() {
            addCriterion("PINDEX is null");
            return (Criteria) this;
        }

        public Criteria andPindexIsNotNull() {
            addCriterion("PINDEX is not null");
            return (Criteria) this;
        }

        public Criteria andPindexEqualTo(Integer value) {
            addCriterion("PINDEX =", value, "pindex");
            return (Criteria) this;
        }

        public Criteria andPindexNotEqualTo(Integer value) {
            addCriterion("PINDEX <>", value, "pindex");
            return (Criteria) this;
        }

        public Criteria andPindexGreaterThan(Integer value) {
            addCriterion("PINDEX >", value, "pindex");
            return (Criteria) this;
        }

        public Criteria andPindexGreaterThanOrEqualTo(Integer value) {
            addCriterion("PINDEX >=", value, "pindex");
            return (Criteria) this;
        }

        public Criteria andPindexLessThan(Integer value) {
            addCriterion("PINDEX <", value, "pindex");
            return (Criteria) this;
        }

        public Criteria andPindexLessThanOrEqualTo(Integer value) {
            addCriterion("PINDEX <=", value, "pindex");
            return (Criteria) this;
        }

        public Criteria andPindexIn(List<Integer> values) {
            addCriterion("PINDEX in", values, "pindex");
            return (Criteria) this;
        }

        public Criteria andPindexNotIn(List<Integer> values) {
            addCriterion("PINDEX not in", values, "pindex");
            return (Criteria) this;
        }

        public Criteria andPindexBetween(Integer value1, Integer value2) {
            addCriterion("PINDEX between", value1, value2, "pindex");
            return (Criteria) this;
        }

        public Criteria andPindexNotBetween(Integer value1, Integer value2) {
            addCriterion("PINDEX not between", value1, value2, "pindex");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNull() {
            addCriterion("ORDER_NO is null");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNotNull() {
            addCriterion("ORDER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNoEqualTo(String value) {
            addCriterion("ORDER_NO =", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotEqualTo(String value) {
            addCriterion("ORDER_NO <>", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThan(String value) {
            addCriterion("ORDER_NO >", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_NO >=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThan(String value) {
            addCriterion("ORDER_NO <", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThanOrEqualTo(String value) {
            addCriterion("ORDER_NO <=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLike(String value) {
            addCriterion("ORDER_NO like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotLike(String value) {
            addCriterion("ORDER_NO not like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoIn(List<String> values) {
            addCriterion("ORDER_NO in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotIn(List<String> values) {
            addCriterion("ORDER_NO not in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoBetween(String value1, String value2) {
            addCriterion("ORDER_NO between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotBetween(String value1, String value2) {
            addCriterion("ORDER_NO not between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andUIdIsNull() {
            addCriterion("U_ID is null");
            return (Criteria) this;
        }

        public Criteria andUIdIsNotNull() {
            addCriterion("U_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUIdEqualTo(String value) {
            addCriterion("U_ID =", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotEqualTo(String value) {
            addCriterion("U_ID <>", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdGreaterThan(String value) {
            addCriterion("U_ID >", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdGreaterThanOrEqualTo(String value) {
            addCriterion("U_ID >=", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdLessThan(String value) {
            addCriterion("U_ID <", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdLessThanOrEqualTo(String value) {
            addCriterion("U_ID <=", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdLike(String value) {
            addCriterion("U_ID like", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotLike(String value) {
            addCriterion("U_ID not like", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdIn(List<String> values) {
            addCriterion("U_ID in", values, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotIn(List<String> values) {
            addCriterion("U_ID not in", values, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdBetween(String value1, String value2) {
            addCriterion("U_ID between", value1, value2, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotBetween(String value1, String value2) {
            addCriterion("U_ID not between", value1, value2, "uId");
            return (Criteria) this;
        }

        public Criteria andLidIsNull() {
            addCriterion("LID is null");
            return (Criteria) this;
        }

        public Criteria andLidIsNotNull() {
            addCriterion("LID is not null");
            return (Criteria) this;
        }

        public Criteria andLidEqualTo(String value) {
            addCriterion("LID =", value, "lid");
            return (Criteria) this;
        }

        public Criteria andLidNotEqualTo(String value) {
            addCriterion("LID <>", value, "lid");
            return (Criteria) this;
        }

        public Criteria andLidGreaterThan(String value) {
            addCriterion("LID >", value, "lid");
            return (Criteria) this;
        }

        public Criteria andLidGreaterThanOrEqualTo(String value) {
            addCriterion("LID >=", value, "lid");
            return (Criteria) this;
        }

        public Criteria andLidLessThan(String value) {
            addCriterion("LID <", value, "lid");
            return (Criteria) this;
        }

        public Criteria andLidLessThanOrEqualTo(String value) {
            addCriterion("LID <=", value, "lid");
            return (Criteria) this;
        }

        public Criteria andLidLike(String value) {
            addCriterion("LID like", value, "lid");
            return (Criteria) this;
        }

        public Criteria andLidNotLike(String value) {
            addCriterion("LID not like", value, "lid");
            return (Criteria) this;
        }

        public Criteria andLidIn(List<String> values) {
            addCriterion("LID in", values, "lid");
            return (Criteria) this;
        }

        public Criteria andLidNotIn(List<String> values) {
            addCriterion("LID not in", values, "lid");
            return (Criteria) this;
        }

        public Criteria andLidBetween(String value1, String value2) {
            addCriterion("LID between", value1, value2, "lid");
            return (Criteria) this;
        }

        public Criteria andLidNotBetween(String value1, String value2) {
            addCriterion("LID not between", value1, value2, "lid");
            return (Criteria) this;
        }

        public Criteria andPrdNameIsNull() {
            addCriterion("PRD_NAME is null");
            return (Criteria) this;
        }

        public Criteria andPrdNameIsNotNull() {
            addCriterion("PRD_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andPrdNameEqualTo(String value) {
            addCriterion("PRD_NAME =", value, "prdName");
            return (Criteria) this;
        }

        public Criteria andPrdNameNotEqualTo(String value) {
            addCriterion("PRD_NAME <>", value, "prdName");
            return (Criteria) this;
        }

        public Criteria andPrdNameGreaterThan(String value) {
            addCriterion("PRD_NAME >", value, "prdName");
            return (Criteria) this;
        }

        public Criteria andPrdNameGreaterThanOrEqualTo(String value) {
            addCriterion("PRD_NAME >=", value, "prdName");
            return (Criteria) this;
        }

        public Criteria andPrdNameLessThan(String value) {
            addCriterion("PRD_NAME <", value, "prdName");
            return (Criteria) this;
        }

        public Criteria andPrdNameLessThanOrEqualTo(String value) {
            addCriterion("PRD_NAME <=", value, "prdName");
            return (Criteria) this;
        }

        public Criteria andPrdNameLike(String value) {
            addCriterion("PRD_NAME like", value, "prdName");
            return (Criteria) this;
        }

        public Criteria andPrdNameNotLike(String value) {
            addCriterion("PRD_NAME not like", value, "prdName");
            return (Criteria) this;
        }

        public Criteria andPrdNameIn(List<String> values) {
            addCriterion("PRD_NAME in", values, "prdName");
            return (Criteria) this;
        }

        public Criteria andPrdNameNotIn(List<String> values) {
            addCriterion("PRD_NAME not in", values, "prdName");
            return (Criteria) this;
        }

        public Criteria andPrdNameBetween(String value1, String value2) {
            addCriterion("PRD_NAME between", value1, value2, "prdName");
            return (Criteria) this;
        }

        public Criteria andPrdNameNotBetween(String value1, String value2) {
            addCriterion("PRD_NAME not between", value1, value2, "prdName");
            return (Criteria) this;
        }

        public Criteria andMerchantIdIsNull() {
            addCriterion("MERCHANT_ID is null");
            return (Criteria) this;
        }

        public Criteria andMerchantIdIsNotNull() {
            addCriterion("MERCHANT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantIdEqualTo(String value) {
            addCriterion("MERCHANT_ID =", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotEqualTo(String value) {
            addCriterion("MERCHANT_ID <>", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdGreaterThan(String value) {
            addCriterion("MERCHANT_ID >", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_ID >=", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdLessThan(String value) {
            addCriterion("MERCHANT_ID <", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdLessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_ID <=", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdLike(String value) {
            addCriterion("MERCHANT_ID like", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotLike(String value) {
            addCriterion("MERCHANT_ID not like", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdIn(List<String> values) {
            addCriterion("MERCHANT_ID in", values, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotIn(List<String> values) {
            addCriterion("MERCHANT_ID not in", values, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdBetween(String value1, String value2) {
            addCriterion("MERCHANT_ID between", value1, value2, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotBetween(String value1, String value2) {
            addCriterion("MERCHANT_ID not between", value1, value2, "merchantId");
            return (Criteria) this;
        }

        public Criteria andTradingNoIsNull() {
            addCriterion("TRADING_NO is null");
            return (Criteria) this;
        }

        public Criteria andTradingNoIsNotNull() {
            addCriterion("TRADING_NO is not null");
            return (Criteria) this;
        }

        public Criteria andTradingNoEqualTo(String value) {
            addCriterion("TRADING_NO =", value, "tradingNo");
            return (Criteria) this;
        }

        public Criteria andTradingNoNotEqualTo(String value) {
            addCriterion("TRADING_NO <>", value, "tradingNo");
            return (Criteria) this;
        }

        public Criteria andTradingNoGreaterThan(String value) {
            addCriterion("TRADING_NO >", value, "tradingNo");
            return (Criteria) this;
        }

        public Criteria andTradingNoGreaterThanOrEqualTo(String value) {
            addCriterion("TRADING_NO >=", value, "tradingNo");
            return (Criteria) this;
        }

        public Criteria andTradingNoLessThan(String value) {
            addCriterion("TRADING_NO <", value, "tradingNo");
            return (Criteria) this;
        }

        public Criteria andTradingNoLessThanOrEqualTo(String value) {
            addCriterion("TRADING_NO <=", value, "tradingNo");
            return (Criteria) this;
        }

        public Criteria andTradingNoLike(String value) {
            addCriterion("TRADING_NO like", value, "tradingNo");
            return (Criteria) this;
        }

        public Criteria andTradingNoNotLike(String value) {
            addCriterion("TRADING_NO not like", value, "tradingNo");
            return (Criteria) this;
        }

        public Criteria andTradingNoIn(List<String> values) {
            addCriterion("TRADING_NO in", values, "tradingNo");
            return (Criteria) this;
        }

        public Criteria andTradingNoNotIn(List<String> values) {
            addCriterion("TRADING_NO not in", values, "tradingNo");
            return (Criteria) this;
        }

        public Criteria andTradingNoBetween(String value1, String value2) {
            addCriterion("TRADING_NO between", value1, value2, "tradingNo");
            return (Criteria) this;
        }

        public Criteria andTradingNoNotBetween(String value1, String value2) {
            addCriterion("TRADING_NO not between", value1, value2, "tradingNo");
            return (Criteria) this;
        }

        public Criteria andSysNoIsNull() {
            addCriterion("SYS_NO is null");
            return (Criteria) this;
        }

        public Criteria andSysNoIsNotNull() {
            addCriterion("SYS_NO is not null");
            return (Criteria) this;
        }

        public Criteria andSysNoEqualTo(String value) {
            addCriterion("SYS_NO =", value, "sysNo");
            return (Criteria) this;
        }

        public Criteria andSysNoNotEqualTo(String value) {
            addCriterion("SYS_NO <>", value, "sysNo");
            return (Criteria) this;
        }

        public Criteria andSysNoGreaterThan(String value) {
            addCriterion("SYS_NO >", value, "sysNo");
            return (Criteria) this;
        }

        public Criteria andSysNoGreaterThanOrEqualTo(String value) {
            addCriterion("SYS_NO >=", value, "sysNo");
            return (Criteria) this;
        }

        public Criteria andSysNoLessThan(String value) {
            addCriterion("SYS_NO <", value, "sysNo");
            return (Criteria) this;
        }

        public Criteria andSysNoLessThanOrEqualTo(String value) {
            addCriterion("SYS_NO <=", value, "sysNo");
            return (Criteria) this;
        }

        public Criteria andSysNoLike(String value) {
            addCriterion("SYS_NO like", value, "sysNo");
            return (Criteria) this;
        }

        public Criteria andSysNoNotLike(String value) {
            addCriterion("SYS_NO not like", value, "sysNo");
            return (Criteria) this;
        }

        public Criteria andSysNoIn(List<String> values) {
            addCriterion("SYS_NO in", values, "sysNo");
            return (Criteria) this;
        }

        public Criteria andSysNoNotIn(List<String> values) {
            addCriterion("SYS_NO not in", values, "sysNo");
            return (Criteria) this;
        }

        public Criteria andSysNoBetween(String value1, String value2) {
            addCriterion("SYS_NO between", value1, value2, "sysNo");
            return (Criteria) this;
        }

        public Criteria andSysNoNotBetween(String value1, String value2) {
            addCriterion("SYS_NO not between", value1, value2, "sysNo");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andRecordCntIsNull() {
            addCriterion("RECORD_CNT is null");
            return (Criteria) this;
        }

        public Criteria andRecordCntIsNotNull() {
            addCriterion("RECORD_CNT is not null");
            return (Criteria) this;
        }

        public Criteria andRecordCntEqualTo(Integer value) {
            addCriterion("RECORD_CNT =", value, "recordCnt");
            return (Criteria) this;
        }

        public Criteria andRecordCntNotEqualTo(Integer value) {
            addCriterion("RECORD_CNT <>", value, "recordCnt");
            return (Criteria) this;
        }

        public Criteria andRecordCntGreaterThan(Integer value) {
            addCriterion("RECORD_CNT >", value, "recordCnt");
            return (Criteria) this;
        }

        public Criteria andRecordCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("RECORD_CNT >=", value, "recordCnt");
            return (Criteria) this;
        }

        public Criteria andRecordCntLessThan(Integer value) {
            addCriterion("RECORD_CNT <", value, "recordCnt");
            return (Criteria) this;
        }

        public Criteria andRecordCntLessThanOrEqualTo(Integer value) {
            addCriterion("RECORD_CNT <=", value, "recordCnt");
            return (Criteria) this;
        }

        public Criteria andRecordCntIn(List<Integer> values) {
            addCriterion("RECORD_CNT in", values, "recordCnt");
            return (Criteria) this;
        }

        public Criteria andRecordCntNotIn(List<Integer> values) {
            addCriterion("RECORD_CNT not in", values, "recordCnt");
            return (Criteria) this;
        }

        public Criteria andRecordCntBetween(Integer value1, Integer value2) {
            addCriterion("RECORD_CNT between", value1, value2, "recordCnt");
            return (Criteria) this;
        }

        public Criteria andRecordCntNotBetween(Integer value1, Integer value2) {
            addCriterion("RECORD_CNT not between", value1, value2, "recordCnt");
            return (Criteria) this;
        }

        public Criteria andLogicFromIsNull() {
            addCriterion("LOGIC_FROM is null");
            return (Criteria) this;
        }

        public Criteria andLogicFromIsNotNull() {
            addCriterion("LOGIC_FROM is not null");
            return (Criteria) this;
        }

        public Criteria andLogicFromEqualTo(String value) {
            addCriterion("LOGIC_FROM =", value, "logicFrom");
            return (Criteria) this;
        }

        public Criteria andLogicFromNotEqualTo(String value) {
            addCriterion("LOGIC_FROM <>", value, "logicFrom");
            return (Criteria) this;
        }

        public Criteria andLogicFromGreaterThan(String value) {
            addCriterion("LOGIC_FROM >", value, "logicFrom");
            return (Criteria) this;
        }

        public Criteria andLogicFromGreaterThanOrEqualTo(String value) {
            addCriterion("LOGIC_FROM >=", value, "logicFrom");
            return (Criteria) this;
        }

        public Criteria andLogicFromLessThan(String value) {
            addCriterion("LOGIC_FROM <", value, "logicFrom");
            return (Criteria) this;
        }

        public Criteria andLogicFromLessThanOrEqualTo(String value) {
            addCriterion("LOGIC_FROM <=", value, "logicFrom");
            return (Criteria) this;
        }

        public Criteria andLogicFromLike(String value) {
            addCriterion("LOGIC_FROM like", value, "logicFrom");
            return (Criteria) this;
        }

        public Criteria andLogicFromNotLike(String value) {
            addCriterion("LOGIC_FROM not like", value, "logicFrom");
            return (Criteria) this;
        }

        public Criteria andLogicFromIn(List<String> values) {
            addCriterion("LOGIC_FROM in", values, "logicFrom");
            return (Criteria) this;
        }

        public Criteria andLogicFromNotIn(List<String> values) {
            addCriterion("LOGIC_FROM not in", values, "logicFrom");
            return (Criteria) this;
        }

        public Criteria andLogicFromBetween(String value1, String value2) {
            addCriterion("LOGIC_FROM between", value1, value2, "logicFrom");
            return (Criteria) this;
        }

        public Criteria andLogicFromNotBetween(String value1, String value2) {
            addCriterion("LOGIC_FROM not between", value1, value2, "logicFrom");
            return (Criteria) this;
        }

        public Criteria andLogicToIsNull() {
            addCriterion("LOGIC_TO is null");
            return (Criteria) this;
        }

        public Criteria andLogicToIsNotNull() {
            addCriterion("LOGIC_TO is not null");
            return (Criteria) this;
        }

        public Criteria andLogicToEqualTo(String value) {
            addCriterion("LOGIC_TO =", value, "logicTo");
            return (Criteria) this;
        }

        public Criteria andLogicToNotEqualTo(String value) {
            addCriterion("LOGIC_TO <>", value, "logicTo");
            return (Criteria) this;
        }

        public Criteria andLogicToGreaterThan(String value) {
            addCriterion("LOGIC_TO >", value, "logicTo");
            return (Criteria) this;
        }

        public Criteria andLogicToGreaterThanOrEqualTo(String value) {
            addCriterion("LOGIC_TO >=", value, "logicTo");
            return (Criteria) this;
        }

        public Criteria andLogicToLessThan(String value) {
            addCriterion("LOGIC_TO <", value, "logicTo");
            return (Criteria) this;
        }

        public Criteria andLogicToLessThanOrEqualTo(String value) {
            addCriterion("LOGIC_TO <=", value, "logicTo");
            return (Criteria) this;
        }

        public Criteria andLogicToLike(String value) {
            addCriterion("LOGIC_TO like", value, "logicTo");
            return (Criteria) this;
        }

        public Criteria andLogicToNotLike(String value) {
            addCriterion("LOGIC_TO not like", value, "logicTo");
            return (Criteria) this;
        }

        public Criteria andLogicToIn(List<String> values) {
            addCriterion("LOGIC_TO in", values, "logicTo");
            return (Criteria) this;
        }

        public Criteria andLogicToNotIn(List<String> values) {
            addCriterion("LOGIC_TO not in", values, "logicTo");
            return (Criteria) this;
        }

        public Criteria andLogicToBetween(String value1, String value2) {
            addCriterion("LOGIC_TO between", value1, value2, "logicTo");
            return (Criteria) this;
        }

        public Criteria andLogicToNotBetween(String value1, String value2) {
            addCriterion("LOGIC_TO not between", value1, value2, "logicTo");
            return (Criteria) this;
        }

        public Criteria andPayTypeIsNull() {
            addCriterion("PAY_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andPayTypeIsNotNull() {
            addCriterion("PAY_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andPayTypeEqualTo(String value) {
            addCriterion("PAY_TYPE =", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeNotEqualTo(String value) {
            addCriterion("PAY_TYPE <>", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeGreaterThan(String value) {
            addCriterion("PAY_TYPE >", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeGreaterThanOrEqualTo(String value) {
            addCriterion("PAY_TYPE >=", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeLessThan(String value) {
            addCriterion("PAY_TYPE <", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeLessThanOrEqualTo(String value) {
            addCriterion("PAY_TYPE <=", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeLike(String value) {
            addCriterion("PAY_TYPE like", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeNotLike(String value) {
            addCriterion("PAY_TYPE not like", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeIn(List<String> values) {
            addCriterion("PAY_TYPE in", values, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeNotIn(List<String> values) {
            addCriterion("PAY_TYPE not in", values, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeBetween(String value1, String value2) {
            addCriterion("PAY_TYPE between", value1, value2, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeNotBetween(String value1, String value2) {
            addCriterion("PAY_TYPE not between", value1, value2, "payType");
            return (Criteria) this;
        }

        public Criteria andPaymentNameIsNull() {
            addCriterion("PAYMENT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andPaymentNameIsNotNull() {
            addCriterion("PAYMENT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentNameEqualTo(String value) {
            addCriterion("PAYMENT_NAME =", value, "paymentName");
            return (Criteria) this;
        }

        public Criteria andPaymentNameNotEqualTo(String value) {
            addCriterion("PAYMENT_NAME <>", value, "paymentName");
            return (Criteria) this;
        }

        public Criteria andPaymentNameGreaterThan(String value) {
            addCriterion("PAYMENT_NAME >", value, "paymentName");
            return (Criteria) this;
        }

        public Criteria andPaymentNameGreaterThanOrEqualTo(String value) {
            addCriterion("PAYMENT_NAME >=", value, "paymentName");
            return (Criteria) this;
        }

        public Criteria andPaymentNameLessThan(String value) {
            addCriterion("PAYMENT_NAME <", value, "paymentName");
            return (Criteria) this;
        }

        public Criteria andPaymentNameLessThanOrEqualTo(String value) {
            addCriterion("PAYMENT_NAME <=", value, "paymentName");
            return (Criteria) this;
        }

        public Criteria andPaymentNameLike(String value) {
            addCriterion("PAYMENT_NAME like", value, "paymentName");
            return (Criteria) this;
        }

        public Criteria andPaymentNameNotLike(String value) {
            addCriterion("PAYMENT_NAME not like", value, "paymentName");
            return (Criteria) this;
        }

        public Criteria andPaymentNameIn(List<String> values) {
            addCriterion("PAYMENT_NAME in", values, "paymentName");
            return (Criteria) this;
        }

        public Criteria andPaymentNameNotIn(List<String> values) {
            addCriterion("PAYMENT_NAME not in", values, "paymentName");
            return (Criteria) this;
        }

        public Criteria andPaymentNameBetween(String value1, String value2) {
            addCriterion("PAYMENT_NAME between", value1, value2, "paymentName");
            return (Criteria) this;
        }

        public Criteria andPaymentNameNotBetween(String value1, String value2) {
            addCriterion("PAYMENT_NAME not between", value1, value2, "paymentName");
            return (Criteria) this;
        }

        public Criteria andPaymentTelIsNull() {
            addCriterion("PAYMENT_TEL is null");
            return (Criteria) this;
        }

        public Criteria andPaymentTelIsNotNull() {
            addCriterion("PAYMENT_TEL is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentTelEqualTo(String value) {
            addCriterion("PAYMENT_TEL =", value, "paymentTel");
            return (Criteria) this;
        }

        public Criteria andPaymentTelNotEqualTo(String value) {
            addCriterion("PAYMENT_TEL <>", value, "paymentTel");
            return (Criteria) this;
        }

        public Criteria andPaymentTelGreaterThan(String value) {
            addCriterion("PAYMENT_TEL >", value, "paymentTel");
            return (Criteria) this;
        }

        public Criteria andPaymentTelGreaterThanOrEqualTo(String value) {
            addCriterion("PAYMENT_TEL >=", value, "paymentTel");
            return (Criteria) this;
        }

        public Criteria andPaymentTelLessThan(String value) {
            addCriterion("PAYMENT_TEL <", value, "paymentTel");
            return (Criteria) this;
        }

        public Criteria andPaymentTelLessThanOrEqualTo(String value) {
            addCriterion("PAYMENT_TEL <=", value, "paymentTel");
            return (Criteria) this;
        }

        public Criteria andPaymentTelLike(String value) {
            addCriterion("PAYMENT_TEL like", value, "paymentTel");
            return (Criteria) this;
        }

        public Criteria andPaymentTelNotLike(String value) {
            addCriterion("PAYMENT_TEL not like", value, "paymentTel");
            return (Criteria) this;
        }

        public Criteria andPaymentTelIn(List<String> values) {
            addCriterion("PAYMENT_TEL in", values, "paymentTel");
            return (Criteria) this;
        }

        public Criteria andPaymentTelNotIn(List<String> values) {
            addCriterion("PAYMENT_TEL not in", values, "paymentTel");
            return (Criteria) this;
        }

        public Criteria andPaymentTelBetween(String value1, String value2) {
            addCriterion("PAYMENT_TEL between", value1, value2, "paymentTel");
            return (Criteria) this;
        }

        public Criteria andPaymentTelNotBetween(String value1, String value2) {
            addCriterion("PAYMENT_TEL not between", value1, value2, "paymentTel");
            return (Criteria) this;
        }

        public Criteria andPaymentIdnoIsNull() {
            addCriterion("PAYMENT_IDNO is null");
            return (Criteria) this;
        }

        public Criteria andPaymentIdnoIsNotNull() {
            addCriterion("PAYMENT_IDNO is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentIdnoEqualTo(String value) {
            addCriterion("PAYMENT_IDNO =", value, "paymentIdno");
            return (Criteria) this;
        }

        public Criteria andPaymentIdnoNotEqualTo(String value) {
            addCriterion("PAYMENT_IDNO <>", value, "paymentIdno");
            return (Criteria) this;
        }

        public Criteria andPaymentIdnoGreaterThan(String value) {
            addCriterion("PAYMENT_IDNO >", value, "paymentIdno");
            return (Criteria) this;
        }

        public Criteria andPaymentIdnoGreaterThanOrEqualTo(String value) {
            addCriterion("PAYMENT_IDNO >=", value, "paymentIdno");
            return (Criteria) this;
        }

        public Criteria andPaymentIdnoLessThan(String value) {
            addCriterion("PAYMENT_IDNO <", value, "paymentIdno");
            return (Criteria) this;
        }

        public Criteria andPaymentIdnoLessThanOrEqualTo(String value) {
            addCriterion("PAYMENT_IDNO <=", value, "paymentIdno");
            return (Criteria) this;
        }

        public Criteria andPaymentIdnoLike(String value) {
            addCriterion("PAYMENT_IDNO like", value, "paymentIdno");
            return (Criteria) this;
        }

        public Criteria andPaymentIdnoNotLike(String value) {
            addCriterion("PAYMENT_IDNO not like", value, "paymentIdno");
            return (Criteria) this;
        }

        public Criteria andPaymentIdnoIn(List<String> values) {
            addCriterion("PAYMENT_IDNO in", values, "paymentIdno");
            return (Criteria) this;
        }

        public Criteria andPaymentIdnoNotIn(List<String> values) {
            addCriterion("PAYMENT_IDNO not in", values, "paymentIdno");
            return (Criteria) this;
        }

        public Criteria andPaymentIdnoBetween(String value1, String value2) {
            addCriterion("PAYMENT_IDNO between", value1, value2, "paymentIdno");
            return (Criteria) this;
        }

        public Criteria andPaymentIdnoNotBetween(String value1, String value2) {
            addCriterion("PAYMENT_IDNO not between", value1, value2, "paymentIdno");
            return (Criteria) this;
        }

        public Criteria andPaymentCardnoIsNull() {
            addCriterion("PAYMENT_CARDNO is null");
            return (Criteria) this;
        }

        public Criteria andPaymentCardnoIsNotNull() {
            addCriterion("PAYMENT_CARDNO is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentCardnoEqualTo(String value) {
            addCriterion("PAYMENT_CARDNO =", value, "paymentCardno");
            return (Criteria) this;
        }

        public Criteria andPaymentCardnoNotEqualTo(String value) {
            addCriterion("PAYMENT_CARDNO <>", value, "paymentCardno");
            return (Criteria) this;
        }

        public Criteria andPaymentCardnoGreaterThan(String value) {
            addCriterion("PAYMENT_CARDNO >", value, "paymentCardno");
            return (Criteria) this;
        }

        public Criteria andPaymentCardnoGreaterThanOrEqualTo(String value) {
            addCriterion("PAYMENT_CARDNO >=", value, "paymentCardno");
            return (Criteria) this;
        }

        public Criteria andPaymentCardnoLessThan(String value) {
            addCriterion("PAYMENT_CARDNO <", value, "paymentCardno");
            return (Criteria) this;
        }

        public Criteria andPaymentCardnoLessThanOrEqualTo(String value) {
            addCriterion("PAYMENT_CARDNO <=", value, "paymentCardno");
            return (Criteria) this;
        }

        public Criteria andPaymentCardnoLike(String value) {
            addCriterion("PAYMENT_CARDNO like", value, "paymentCardno");
            return (Criteria) this;
        }

        public Criteria andPaymentCardnoNotLike(String value) {
            addCriterion("PAYMENT_CARDNO not like", value, "paymentCardno");
            return (Criteria) this;
        }

        public Criteria andPaymentCardnoIn(List<String> values) {
            addCriterion("PAYMENT_CARDNO in", values, "paymentCardno");
            return (Criteria) this;
        }

        public Criteria andPaymentCardnoNotIn(List<String> values) {
            addCriterion("PAYMENT_CARDNO not in", values, "paymentCardno");
            return (Criteria) this;
        }

        public Criteria andPaymentCardnoBetween(String value1, String value2) {
            addCriterion("PAYMENT_CARDNO between", value1, value2, "paymentCardno");
            return (Criteria) this;
        }

        public Criteria andPaymentCardnoNotBetween(String value1, String value2) {
            addCriterion("PAYMENT_CARDNO not between", value1, value2, "paymentCardno");
            return (Criteria) this;
        }

        public Criteria andPaymentBankcodeIsNull() {
            addCriterion("PAYMENT_BANKCODE is null");
            return (Criteria) this;
        }

        public Criteria andPaymentBankcodeIsNotNull() {
            addCriterion("PAYMENT_BANKCODE is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentBankcodeEqualTo(String value) {
            addCriterion("PAYMENT_BANKCODE =", value, "paymentBankcode");
            return (Criteria) this;
        }

        public Criteria andPaymentBankcodeNotEqualTo(String value) {
            addCriterion("PAYMENT_BANKCODE <>", value, "paymentBankcode");
            return (Criteria) this;
        }

        public Criteria andPaymentBankcodeGreaterThan(String value) {
            addCriterion("PAYMENT_BANKCODE >", value, "paymentBankcode");
            return (Criteria) this;
        }

        public Criteria andPaymentBankcodeGreaterThanOrEqualTo(String value) {
            addCriterion("PAYMENT_BANKCODE >=", value, "paymentBankcode");
            return (Criteria) this;
        }

        public Criteria andPaymentBankcodeLessThan(String value) {
            addCriterion("PAYMENT_BANKCODE <", value, "paymentBankcode");
            return (Criteria) this;
        }

        public Criteria andPaymentBankcodeLessThanOrEqualTo(String value) {
            addCriterion("PAYMENT_BANKCODE <=", value, "paymentBankcode");
            return (Criteria) this;
        }

        public Criteria andPaymentBankcodeLike(String value) {
            addCriterion("PAYMENT_BANKCODE like", value, "paymentBankcode");
            return (Criteria) this;
        }

        public Criteria andPaymentBankcodeNotLike(String value) {
            addCriterion("PAYMENT_BANKCODE not like", value, "paymentBankcode");
            return (Criteria) this;
        }

        public Criteria andPaymentBankcodeIn(List<String> values) {
            addCriterion("PAYMENT_BANKCODE in", values, "paymentBankcode");
            return (Criteria) this;
        }

        public Criteria andPaymentBankcodeNotIn(List<String> values) {
            addCriterion("PAYMENT_BANKCODE not in", values, "paymentBankcode");
            return (Criteria) this;
        }

        public Criteria andPaymentBankcodeBetween(String value1, String value2) {
            addCriterion("PAYMENT_BANKCODE between", value1, value2, "paymentBankcode");
            return (Criteria) this;
        }

        public Criteria andPaymentBankcodeNotBetween(String value1, String value2) {
            addCriterion("PAYMENT_BANKCODE not between", value1, value2, "paymentBankcode");
            return (Criteria) this;
        }

        public Criteria andTotalAmountIsNull() {
            addCriterion("TOTAL_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andTotalAmountIsNotNull() {
            addCriterion("TOTAL_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andTotalAmountEqualTo(BigDecimal value) {
            addCriterion("TOTAL_AMOUNT =", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountNotEqualTo(BigDecimal value) {
            addCriterion("TOTAL_AMOUNT <>", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountGreaterThan(BigDecimal value) {
            addCriterion("TOTAL_AMOUNT >", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTAL_AMOUNT >=", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountLessThan(BigDecimal value) {
            addCriterion("TOTAL_AMOUNT <", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTAL_AMOUNT <=", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountIn(List<BigDecimal> values) {
            addCriterion("TOTAL_AMOUNT in", values, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountNotIn(List<BigDecimal> values) {
            addCriterion("TOTAL_AMOUNT not in", values, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTAL_AMOUNT between", value1, value2, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTAL_AMOUNT not between", value1, value2, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andIoFlagIsNull() {
            addCriterion("IO_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andIoFlagIsNotNull() {
            addCriterion("IO_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andIoFlagEqualTo(String value) {
            addCriterion("IO_FLAG =", value, "ioFlag");
            return (Criteria) this;
        }

        public Criteria andIoFlagNotEqualTo(String value) {
            addCriterion("IO_FLAG <>", value, "ioFlag");
            return (Criteria) this;
        }

        public Criteria andIoFlagGreaterThan(String value) {
            addCriterion("IO_FLAG >", value, "ioFlag");
            return (Criteria) this;
        }

        public Criteria andIoFlagGreaterThanOrEqualTo(String value) {
            addCriterion("IO_FLAG >=", value, "ioFlag");
            return (Criteria) this;
        }

        public Criteria andIoFlagLessThan(String value) {
            addCriterion("IO_FLAG <", value, "ioFlag");
            return (Criteria) this;
        }

        public Criteria andIoFlagLessThanOrEqualTo(String value) {
            addCriterion("IO_FLAG <=", value, "ioFlag");
            return (Criteria) this;
        }

        public Criteria andIoFlagLike(String value) {
            addCriterion("IO_FLAG like", value, "ioFlag");
            return (Criteria) this;
        }

        public Criteria andIoFlagNotLike(String value) {
            addCriterion("IO_FLAG not like", value, "ioFlag");
            return (Criteria) this;
        }

        public Criteria andIoFlagIn(List<String> values) {
            addCriterion("IO_FLAG in", values, "ioFlag");
            return (Criteria) this;
        }

        public Criteria andIoFlagNotIn(List<String> values) {
            addCriterion("IO_FLAG not in", values, "ioFlag");
            return (Criteria) this;
        }

        public Criteria andIoFlagBetween(String value1, String value2) {
            addCriterion("IO_FLAG between", value1, value2, "ioFlag");
            return (Criteria) this;
        }

        public Criteria andIoFlagNotBetween(String value1, String value2) {
            addCriterion("IO_FLAG not between", value1, value2, "ioFlag");
            return (Criteria) this;
        }

        public Criteria andPaymentChannelsIsNull() {
            addCriterion("PAYMENT_CHANNELS is null");
            return (Criteria) this;
        }

        public Criteria andPaymentChannelsIsNotNull() {
            addCriterion("PAYMENT_CHANNELS is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentChannelsEqualTo(String value) {
            addCriterion("PAYMENT_CHANNELS =", value, "paymentChannels");
            return (Criteria) this;
        }

        public Criteria andPaymentChannelsNotEqualTo(String value) {
            addCriterion("PAYMENT_CHANNELS <>", value, "paymentChannels");
            return (Criteria) this;
        }

        public Criteria andPaymentChannelsGreaterThan(String value) {
            addCriterion("PAYMENT_CHANNELS >", value, "paymentChannels");
            return (Criteria) this;
        }

        public Criteria andPaymentChannelsGreaterThanOrEqualTo(String value) {
            addCriterion("PAYMENT_CHANNELS >=", value, "paymentChannels");
            return (Criteria) this;
        }

        public Criteria andPaymentChannelsLessThan(String value) {
            addCriterion("PAYMENT_CHANNELS <", value, "paymentChannels");
            return (Criteria) this;
        }

        public Criteria andPaymentChannelsLessThanOrEqualTo(String value) {
            addCriterion("PAYMENT_CHANNELS <=", value, "paymentChannels");
            return (Criteria) this;
        }

        public Criteria andPaymentChannelsLike(String value) {
            addCriterion("PAYMENT_CHANNELS like", value, "paymentChannels");
            return (Criteria) this;
        }

        public Criteria andPaymentChannelsNotLike(String value) {
            addCriterion("PAYMENT_CHANNELS not like", value, "paymentChannels");
            return (Criteria) this;
        }

        public Criteria andPaymentChannelsIn(List<String> values) {
            addCriterion("PAYMENT_CHANNELS in", values, "paymentChannels");
            return (Criteria) this;
        }

        public Criteria andPaymentChannelsNotIn(List<String> values) {
            addCriterion("PAYMENT_CHANNELS not in", values, "paymentChannels");
            return (Criteria) this;
        }

        public Criteria andPaymentChannelsBetween(String value1, String value2) {
            addCriterion("PAYMENT_CHANNELS between", value1, value2, "paymentChannels");
            return (Criteria) this;
        }

        public Criteria andPaymentChannelsNotBetween(String value1, String value2) {
            addCriterion("PAYMENT_CHANNELS not between", value1, value2, "paymentChannels");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("CREATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("CREATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("CREATE_USER =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("CREATE_USER <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("CREATE_USER >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("CREATE_USER <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("CREATE_USER like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("CREATE_USER not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("CREATE_USER in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("CREATE_USER not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("CREATE_USER between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andClientipIsNull() {
            addCriterion("CLIENTIP is null");
            return (Criteria) this;
        }

        public Criteria andClientipIsNotNull() {
            addCriterion("CLIENTIP is not null");
            return (Criteria) this;
        }

        public Criteria andClientipEqualTo(String value) {
            addCriterion("CLIENTIP =", value, "clientip");
            return (Criteria) this;
        }

        public Criteria andClientipNotEqualTo(String value) {
            addCriterion("CLIENTIP <>", value, "clientip");
            return (Criteria) this;
        }

        public Criteria andClientipGreaterThan(String value) {
            addCriterion("CLIENTIP >", value, "clientip");
            return (Criteria) this;
        }

        public Criteria andClientipGreaterThanOrEqualTo(String value) {
            addCriterion("CLIENTIP >=", value, "clientip");
            return (Criteria) this;
        }

        public Criteria andClientipLessThan(String value) {
            addCriterion("CLIENTIP <", value, "clientip");
            return (Criteria) this;
        }

        public Criteria andClientipLessThanOrEqualTo(String value) {
            addCriterion("CLIENTIP <=", value, "clientip");
            return (Criteria) this;
        }

        public Criteria andClientipLike(String value) {
            addCriterion("CLIENTIP like", value, "clientip");
            return (Criteria) this;
        }

        public Criteria andClientipNotLike(String value) {
            addCriterion("CLIENTIP not like", value, "clientip");
            return (Criteria) this;
        }

        public Criteria andClientipIn(List<String> values) {
            addCriterion("CLIENTIP in", values, "clientip");
            return (Criteria) this;
        }

        public Criteria andClientipNotIn(List<String> values) {
            addCriterion("CLIENTIP not in", values, "clientip");
            return (Criteria) this;
        }

        public Criteria andClientipBetween(String value1, String value2) {
            addCriterion("CLIENTIP between", value1, value2, "clientip");
            return (Criteria) this;
        }

        public Criteria andClientipNotBetween(String value1, String value2) {
            addCriterion("CLIENTIP not between", value1, value2, "clientip");
            return (Criteria) this;
        }

        public Criteria andRemark1IsNull() {
            addCriterion("REMARK1 is null");
            return (Criteria) this;
        }

        public Criteria andRemark1IsNotNull() {
            addCriterion("REMARK1 is not null");
            return (Criteria) this;
        }

        public Criteria andRemark1EqualTo(String value) {
            addCriterion("REMARK1 =", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1NotEqualTo(String value) {
            addCriterion("REMARK1 <>", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1GreaterThan(String value) {
            addCriterion("REMARK1 >", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1GreaterThanOrEqualTo(String value) {
            addCriterion("REMARK1 >=", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1LessThan(String value) {
            addCriterion("REMARK1 <", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1LessThanOrEqualTo(String value) {
            addCriterion("REMARK1 <=", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1Like(String value) {
            addCriterion("REMARK1 like", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1NotLike(String value) {
            addCriterion("REMARK1 not like", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1In(List<String> values) {
            addCriterion("REMARK1 in", values, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1NotIn(List<String> values) {
            addCriterion("REMARK1 not in", values, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1Between(String value1, String value2) {
            addCriterion("REMARK1 between", value1, value2, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1NotBetween(String value1, String value2) {
            addCriterion("REMARK1 not between", value1, value2, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark2IsNull() {
            addCriterion("REMARK2 is null");
            return (Criteria) this;
        }

        public Criteria andRemark2IsNotNull() {
            addCriterion("REMARK2 is not null");
            return (Criteria) this;
        }

        public Criteria andRemark2EqualTo(String value) {
            addCriterion("REMARK2 =", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2NotEqualTo(String value) {
            addCriterion("REMARK2 <>", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2GreaterThan(String value) {
            addCriterion("REMARK2 >", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2GreaterThanOrEqualTo(String value) {
            addCriterion("REMARK2 >=", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2LessThan(String value) {
            addCriterion("REMARK2 <", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2LessThanOrEqualTo(String value) {
            addCriterion("REMARK2 <=", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2Like(String value) {
            addCriterion("REMARK2 like", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2NotLike(String value) {
            addCriterion("REMARK2 not like", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2In(List<String> values) {
            addCriterion("REMARK2 in", values, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2NotIn(List<String> values) {
            addCriterion("REMARK2 not in", values, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2Between(String value1, String value2) {
            addCriterion("REMARK2 between", value1, value2, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2NotBetween(String value1, String value2) {
            addCriterion("REMARK2 not between", value1, value2, "remark2");
            return (Criteria) this;
        }

        public Criteria andTxcodeIsNull() {
            addCriterion("TXCODE is null");
            return (Criteria) this;
        }

        public Criteria andTxcodeIsNotNull() {
            addCriterion("TXCODE is not null");
            return (Criteria) this;
        }

        public Criteria andTxcodeEqualTo(String value) {
            addCriterion("TXCODE =", value, "txcode");
            return (Criteria) this;
        }

        public Criteria andTxcodeNotEqualTo(String value) {
            addCriterion("TXCODE <>", value, "txcode");
            return (Criteria) this;
        }

        public Criteria andTxcodeGreaterThan(String value) {
            addCriterion("TXCODE >", value, "txcode");
            return (Criteria) this;
        }

        public Criteria andTxcodeGreaterThanOrEqualTo(String value) {
            addCriterion("TXCODE >=", value, "txcode");
            return (Criteria) this;
        }

        public Criteria andTxcodeLessThan(String value) {
            addCriterion("TXCODE <", value, "txcode");
            return (Criteria) this;
        }

        public Criteria andTxcodeLessThanOrEqualTo(String value) {
            addCriterion("TXCODE <=", value, "txcode");
            return (Criteria) this;
        }

        public Criteria andTxcodeLike(String value) {
            addCriterion("TXCODE like", value, "txcode");
            return (Criteria) this;
        }

        public Criteria andTxcodeNotLike(String value) {
            addCriterion("TXCODE not like", value, "txcode");
            return (Criteria) this;
        }

        public Criteria andTxcodeIn(List<String> values) {
            addCriterion("TXCODE in", values, "txcode");
            return (Criteria) this;
        }

        public Criteria andTxcodeNotIn(List<String> values) {
            addCriterion("TXCODE not in", values, "txcode");
            return (Criteria) this;
        }

        public Criteria andTxcodeBetween(String value1, String value2) {
            addCriterion("TXCODE between", value1, value2, "txcode");
            return (Criteria) this;
        }

        public Criteria andTxcodeNotBetween(String value1, String value2) {
            addCriterion("TXCODE not between", value1, value2, "txcode");
            return (Criteria) this;
        }

        public Criteria andInstallnumIsNull() {
            addCriterion("INSTALLNUM is null");
            return (Criteria) this;
        }

        public Criteria andInstallnumIsNotNull() {
            addCriterion("INSTALLNUM is not null");
            return (Criteria) this;
        }

        public Criteria andInstallnumEqualTo(Integer value) {
            addCriterion("INSTALLNUM =", value, "installnum");
            return (Criteria) this;
        }

        public Criteria andInstallnumNotEqualTo(Integer value) {
            addCriterion("INSTALLNUM <>", value, "installnum");
            return (Criteria) this;
        }

        public Criteria andInstallnumGreaterThan(Integer value) {
            addCriterion("INSTALLNUM >", value, "installnum");
            return (Criteria) this;
        }

        public Criteria andInstallnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("INSTALLNUM >=", value, "installnum");
            return (Criteria) this;
        }

        public Criteria andInstallnumLessThan(Integer value) {
            addCriterion("INSTALLNUM <", value, "installnum");
            return (Criteria) this;
        }

        public Criteria andInstallnumLessThanOrEqualTo(Integer value) {
            addCriterion("INSTALLNUM <=", value, "installnum");
            return (Criteria) this;
        }

        public Criteria andInstallnumIn(List<Integer> values) {
            addCriterion("INSTALLNUM in", values, "installnum");
            return (Criteria) this;
        }

        public Criteria andInstallnumNotIn(List<Integer> values) {
            addCriterion("INSTALLNUM not in", values, "installnum");
            return (Criteria) this;
        }

        public Criteria andInstallnumBetween(Integer value1, Integer value2) {
            addCriterion("INSTALLNUM between", value1, value2, "installnum");
            return (Criteria) this;
        }

        public Criteria andInstallnumNotBetween(Integer value1, Integer value2) {
            addCriterion("INSTALLNUM not between", value1, value2, "installnum");
            return (Criteria) this;
        }

        public Criteria andIsRefundIsNull() {
            addCriterion("IS_REFUND is null");
            return (Criteria) this;
        }

        public Criteria andIsRefundIsNotNull() {
            addCriterion("IS_REFUND is not null");
            return (Criteria) this;
        }

        public Criteria andIsRefundEqualTo(String value) {
            addCriterion("IS_REFUND =", value, "isRefund");
            return (Criteria) this;
        }

        public Criteria andIsRefundNotEqualTo(String value) {
            addCriterion("IS_REFUND <>", value, "isRefund");
            return (Criteria) this;
        }

        public Criteria andIsRefundGreaterThan(String value) {
            addCriterion("IS_REFUND >", value, "isRefund");
            return (Criteria) this;
        }

        public Criteria andIsRefundGreaterThanOrEqualTo(String value) {
            addCriterion("IS_REFUND >=", value, "isRefund");
            return (Criteria) this;
        }

        public Criteria andIsRefundLessThan(String value) {
            addCriterion("IS_REFUND <", value, "isRefund");
            return (Criteria) this;
        }

        public Criteria andIsRefundLessThanOrEqualTo(String value) {
            addCriterion("IS_REFUND <=", value, "isRefund");
            return (Criteria) this;
        }

        public Criteria andIsRefundLike(String value) {
            addCriterion("IS_REFUND like", value, "isRefund");
            return (Criteria) this;
        }

        public Criteria andIsRefundNotLike(String value) {
            addCriterion("IS_REFUND not like", value, "isRefund");
            return (Criteria) this;
        }

        public Criteria andIsRefundIn(List<String> values) {
            addCriterion("IS_REFUND in", values, "isRefund");
            return (Criteria) this;
        }

        public Criteria andIsRefundNotIn(List<String> values) {
            addCriterion("IS_REFUND not in", values, "isRefund");
            return (Criteria) this;
        }

        public Criteria andIsRefundBetween(String value1, String value2) {
            addCriterion("IS_REFUND between", value1, value2, "isRefund");
            return (Criteria) this;
        }

        public Criteria andIsRefundNotBetween(String value1, String value2) {
            addCriterion("IS_REFUND not between", value1, value2, "isRefund");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdentityIsNull() {
            addCriterion("CREATE_USER_IDENTITY is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdentityIsNotNull() {
            addCriterion("CREATE_USER_IDENTITY is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdentityEqualTo(Short value) {
            addCriterion("CREATE_USER_IDENTITY =", value, "createUserIdentity");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdentityNotEqualTo(Short value) {
            addCriterion("CREATE_USER_IDENTITY <>", value, "createUserIdentity");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdentityGreaterThan(Short value) {
            addCriterion("CREATE_USER_IDENTITY >", value, "createUserIdentity");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdentityGreaterThanOrEqualTo(Short value) {
            addCriterion("CREATE_USER_IDENTITY >=", value, "createUserIdentity");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdentityLessThan(Short value) {
            addCriterion("CREATE_USER_IDENTITY <", value, "createUserIdentity");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdentityLessThanOrEqualTo(Short value) {
            addCriterion("CREATE_USER_IDENTITY <=", value, "createUserIdentity");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdentityIn(List<Short> values) {
            addCriterion("CREATE_USER_IDENTITY in", values, "createUserIdentity");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdentityNotIn(List<Short> values) {
            addCriterion("CREATE_USER_IDENTITY not in", values, "createUserIdentity");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdentityBetween(Short value1, Short value2) {
            addCriterion("CREATE_USER_IDENTITY between", value1, value2, "createUserIdentity");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdentityNotBetween(Short value1, Short value2) {
            addCriterion("CREATE_USER_IDENTITY not between", value1, value2, "createUserIdentity");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNull() {
            addCriterion("MODIFY_USER is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNotNull() {
            addCriterion("MODIFY_USER is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserEqualTo(String value) {
            addCriterion("MODIFY_USER =", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotEqualTo(String value) {
            addCriterion("MODIFY_USER <>", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThan(String value) {
            addCriterion("MODIFY_USER >", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFY_USER >=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThan(String value) {
            addCriterion("MODIFY_USER <", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThanOrEqualTo(String value) {
            addCriterion("MODIFY_USER <=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLike(String value) {
            addCriterion("MODIFY_USER like", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotLike(String value) {
            addCriterion("MODIFY_USER not like", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserIn(List<String> values) {
            addCriterion("MODIFY_USER in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotIn(List<String> values) {
            addCriterion("MODIFY_USER not in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserBetween(String value1, String value2) {
            addCriterion("MODIFY_USER between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotBetween(String value1, String value2) {
            addCriterion("MODIFY_USER not between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdentityIsNull() {
            addCriterion("MODIFY_USER_IDENTITY is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdentityIsNotNull() {
            addCriterion("MODIFY_USER_IDENTITY is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdentityEqualTo(Short value) {
            addCriterion("MODIFY_USER_IDENTITY =", value, "modifyUserIdentity");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdentityNotEqualTo(Short value) {
            addCriterion("MODIFY_USER_IDENTITY <>", value, "modifyUserIdentity");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdentityGreaterThan(Short value) {
            addCriterion("MODIFY_USER_IDENTITY >", value, "modifyUserIdentity");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdentityGreaterThanOrEqualTo(Short value) {
            addCriterion("MODIFY_USER_IDENTITY >=", value, "modifyUserIdentity");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdentityLessThan(Short value) {
            addCriterion("MODIFY_USER_IDENTITY <", value, "modifyUserIdentity");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdentityLessThanOrEqualTo(Short value) {
            addCriterion("MODIFY_USER_IDENTITY <=", value, "modifyUserIdentity");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdentityIn(List<Short> values) {
            addCriterion("MODIFY_USER_IDENTITY in", values, "modifyUserIdentity");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdentityNotIn(List<Short> values) {
            addCriterion("MODIFY_USER_IDENTITY not in", values, "modifyUserIdentity");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdentityBetween(Short value1, Short value2) {
            addCriterion("MODIFY_USER_IDENTITY between", value1, value2, "modifyUserIdentity");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdentityNotBetween(Short value1, Short value2) {
            addCriterion("MODIFY_USER_IDENTITY not between", value1, value2, "modifyUserIdentity");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("MODIFY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("MODIFY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("MODIFY_TIME =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("MODIFY_TIME <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("MODIFY_TIME >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("MODIFY_TIME <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("MODIFY_TIME in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("MODIFY_TIME not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIsNull() {
            addCriterion("DELETE_FLG is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIsNotNull() {
            addCriterion("DELETE_FLG is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgEqualTo(Short value) {
            addCriterion("DELETE_FLG =", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotEqualTo(Short value) {
            addCriterion("DELETE_FLG <>", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgGreaterThan(Short value) {
            addCriterion("DELETE_FLG >", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgGreaterThanOrEqualTo(Short value) {
            addCriterion("DELETE_FLG >=", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLessThan(Short value) {
            addCriterion("DELETE_FLG <", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLessThanOrEqualTo(Short value) {
            addCriterion("DELETE_FLG <=", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIn(List<Short> values) {
            addCriterion("DELETE_FLG in", values, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotIn(List<Short> values) {
            addCriterion("DELETE_FLG not in", values, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgBetween(Short value1, Short value2) {
            addCriterion("DELETE_FLG between", value1, value2, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotBetween(Short value1, Short value2) {
            addCriterion("DELETE_FLG not between", value1, value2, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("VERSION =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("VERSION <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("VERSION >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("VERSION >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("VERSION <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("VERSION <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("VERSION in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("VERSION not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("VERSION between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("VERSION not between", value1, value2, "version");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_order
     *
     * @mbggenerated do_not_delete_during_merge Sat Jun 03 13:24:30 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_order
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}