package com.dlfc.system.entity;

import com.dlfc.system.common.DataEntity;

import java.util.Date;

public class SysTradeAreas extends DataEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_trade_areas.ID
     *
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_trade_areas.PINDEX
     *
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    private Integer pindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_trade_areas.TRADE_ID
     *
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    private String tradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_trade_areas.NAME
     *
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_trade_areas.S_SPELL
     *
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    private String sSpell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_trade_areas.PARENT_ID
     *
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_trade_areas.CREATE_USER
     *
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_trade_areas.CREATE_USER_IDENTITY
     *
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    private Short createUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_trade_areas.CREATE_TIME
     *
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_trade_areas.MODIFY_USER
     *
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_trade_areas.MODIFY_USER_IDENTITY
     *
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    private Short modifyUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_trade_areas.MODIFY_TIME
     *
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_trade_areas.DELETE_FLG
     *
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    private Short deleteFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_trade_areas.VERSION
     *
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_trade_areas.ID
     *
     * @return the value of sys_trade_areas.ID
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_trade_areas.ID
     *
     * @param id the value for sys_trade_areas.ID
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_trade_areas.PINDEX
     *
     * @return the value of sys_trade_areas.PINDEX
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    public Integer getPindex() {
        return pindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_trade_areas.PINDEX
     *
     * @param pindex the value for sys_trade_areas.PINDEX
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    public void setPindex(Integer pindex) {
        this.pindex = pindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_trade_areas.TRADE_ID
     *
     * @return the value of sys_trade_areas.TRADE_ID
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    public String getTradeId() {
        return tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_trade_areas.TRADE_ID
     *
     * @param tradeId the value for sys_trade_areas.TRADE_ID
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    public void setTradeId(String tradeId) {
        this.tradeId = tradeId == null ? null : tradeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_trade_areas.NAME
     *
     * @return the value of sys_trade_areas.NAME
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_trade_areas.NAME
     *
     * @param name the value for sys_trade_areas.NAME
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_trade_areas.S_SPELL
     *
     * @return the value of sys_trade_areas.S_SPELL
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    public String getsSpell() {
        return sSpell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_trade_areas.S_SPELL
     *
     * @param sSpell the value for sys_trade_areas.S_SPELL
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    public void setsSpell(String sSpell) {
        this.sSpell = sSpell == null ? null : sSpell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_trade_areas.PARENT_ID
     *
     * @return the value of sys_trade_areas.PARENT_ID
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_trade_areas.PARENT_ID
     *
     * @param parentId the value for sys_trade_areas.PARENT_ID
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_trade_areas.CREATE_USER
     *
     * @return the value of sys_trade_areas.CREATE_USER
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_trade_areas.CREATE_USER
     *
     * @param createUser the value for sys_trade_areas.CREATE_USER
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_trade_areas.CREATE_USER_IDENTITY
     *
     * @return the value of sys_trade_areas.CREATE_USER_IDENTITY
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    public Short getCreateUserIdentity() {
        return createUserIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_trade_areas.CREATE_USER_IDENTITY
     *
     * @param createUserIdentity the value for sys_trade_areas.CREATE_USER_IDENTITY
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    public void setCreateUserIdentity(Short createUserIdentity) {
        this.createUserIdentity = createUserIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_trade_areas.CREATE_TIME
     *
     * @return the value of sys_trade_areas.CREATE_TIME
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_trade_areas.CREATE_TIME
     *
     * @param createTime the value for sys_trade_areas.CREATE_TIME
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_trade_areas.MODIFY_USER
     *
     * @return the value of sys_trade_areas.MODIFY_USER
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_trade_areas.MODIFY_USER
     *
     * @param modifyUser the value for sys_trade_areas.MODIFY_USER
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_trade_areas.MODIFY_USER_IDENTITY
     *
     * @return the value of sys_trade_areas.MODIFY_USER_IDENTITY
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    public Short getModifyUserIdentity() {
        return modifyUserIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_trade_areas.MODIFY_USER_IDENTITY
     *
     * @param modifyUserIdentity the value for sys_trade_areas.MODIFY_USER_IDENTITY
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    public void setModifyUserIdentity(Short modifyUserIdentity) {
        this.modifyUserIdentity = modifyUserIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_trade_areas.MODIFY_TIME
     *
     * @return the value of sys_trade_areas.MODIFY_TIME
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_trade_areas.MODIFY_TIME
     *
     * @param modifyTime the value for sys_trade_areas.MODIFY_TIME
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_trade_areas.DELETE_FLG
     *
     * @return the value of sys_trade_areas.DELETE_FLG
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    public Short getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_trade_areas.DELETE_FLG
     *
     * @param deleteFlg the value for sys_trade_areas.DELETE_FLG
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    public void setDeleteFlg(Short deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_trade_areas.VERSION
     *
     * @return the value of sys_trade_areas.VERSION
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_trade_areas.VERSION
     *
     * @param version the value for sys_trade_areas.VERSION
     * @mbggenerated Mon May 29 16:03:04 CST 2017
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}