server:
  port: 18082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dlfc_155
    username: root
    password: root
mybatis:
  config-location: classpath:mybatis-config.xml
  mapperLocations: classpath:mappings/*.xml
